theworldphone/modules/admin/forms.py
# -*- coding: utf-8 -*-
"""
    theworldphone.modules.admin.forms
    ~~~~~~~~~~~~~~~~

    admin module forms
"""

from flask.ext.wtf import Form
from wtforms import (HiddenField, SubmitField, SelectField, FileField, DateField)
from wtforms.validators import AnyOf

from theworldphone.extensions import db
from theworldphone.modules.user.constants import UserStatus


class UserForm(Form):
    next = HiddenField()
    status = SelectField(u"Status", [AnyOf([str(s.name) for s in UserStatus])],
            choices=[(str(s.name), s.name.capitalize()) for s in UserStatus])
    created_time = DateField(u'Created time')  # _created_at ?
    submit = SubmitField(u'Save')

    def save(self, user):
        self.populate_obj(user)
        db.session.add(user)
        db.session.commit()


class EditTranslationForm(Form):
    multipart = True
    file = FileField(u"Upload Translation File")
    language = HiddenField()
    submit = SubmitField(u'Save')

theworldphone/__init__.py
# -*- coding: utf-8 -*-

from factory import create_app

theworldphone/modules/admin/__init__.py
# -*- coding: utf-8 -*-

from .views import admin

__all__ = [admin]

theworldphone/modules/admin/views.py
# -*- coding: utf-8 -*-
"""
    theworldphone.modules.admin.views
    ~~~~~~~~~~~~~~~~

    admin module views and controllers
"""

from werkzeug import secure_filename
import os, json, urllib, re, requests, time, datetime

from itertools import chain

from flask import (Blueprint, render_template, request, flash, current_app, send_from_directory,
    redirect, url_for, jsonify, abort)
from flask.ext.login import login_required, login_user, logout_user, current_user
from flask.ext.babel import Babel

from theworldphone.extensions import db
from theworldphone.decorators import admin_required

from theworldphone.modules.frontend.forms import LoginForm
from theworldphone.modules.redis import RedisQueue
from theworldphone.modules.user.models import User, Language
from theworldphone.modules.user.constants import UserRole, COUNTRY_CODES
from theworldphone.modules.call import CallLog
from theworldphone.modules.call.constants import CallType

from .forms import UserForm, EditTranslationForm

admin = Blueprint('admin', __name__, url_prefix='/admin')


# flash(_( -> flash((

@admin.route('/login', methods=['GET', 'POST'])
def login():
    '''
    If user is not logged in:

    1) Show the user the login form.
    2) Handle the input form the login form.

    If user is already logged, send them to user.index or admin.index as appropriate

    If User.authenticate(form.login.data, form.password.data) checks out
    send them to user.index or admin.index as appropriate.

    If the user is banned, flash a message and reshow login form.

    '''
    if current_user.is_authenticated and not current_user.is_admin():
        return redirect(url_for('user.index'))
    elif current_user.is_authenticated and current_user.is_admin():
        return redirect(url_for('admin.index'))

    form = LoginForm(login=request.args.get('login', None),
                     next=request.args.get('next', None))

    if form.validate_on_submit():
        user, authenticated = User.authenticate(form.login.data,
                                    form.password.data)
        if user and authenticated and user.status == 'banned':
            flash(('Sorry, you are not allowed access to your account due to inappropriate behavior.'), 'danger')
        elif user and authenticated and user.status == 'active':
            remember = request.form.get('remember') == 'y'
            if login_user(user, remember=remember):

                if request.environ.get('HTTP_X_REAL_IP', request.remote_addr) not in user._ip_list.values():
                    user._ip_list[datetime.datetime.now()] = request.environ.get('HTTP_X_REAL_IP', request.remote_addr)
                    db.session.commit()

                flash(("Logged in"), 'success')
            if user.is_admin():
                return redirect(url_for('admin.index'))
            else:
                return redirect(form.next.data or url_for('user.index'))
        else:
            flash(('Sorry, invalid login'), 'danger')

    return render_template('frontend/login.html', form=form)


@admin.route('/reauth', methods=['GET', 'POST'])
@login_required
def reauth():
    '''This function allows a user to attempt to log in
    again after a failed attempt.

    **Returns:**
        - Change password view on reauthentication success
        - Reauthentication view on reauthentication failure.

    '''
    form = ReauthForm(next=request.args.get('next'))

    if request.method == 'POST':
        user, authenticated = User.authenticate(current_user.name,
                                    form.password.data)
        if user and authenticated:
            confirm_login()
            current_app.logger.debug('reauth: %s' % session['_fresh'])
            flash(('Reauthenticated.'), 'success')
            return redirect('/change_password')

        flash(('Password is wrong.'), 'danger')
    return render_template('frontend/reauth.html', form=form)


@admin.route('/logout')
@login_required
def logout():
    '''This function logs user out of current session.

    Returns:
        Redirects to login view on success.

    '''
    logout_user()
    flash(('Logged out'), 'success')
    return redirect(url_for('admin.login'))


@admin.route('/')
@login_required
@admin_required
def index():
    """
    # Grab TEFL_PENDING users and flagged calls.
    Grab all users.
    Use those to load admin index page.

    # Returns render_template('admin/index.html', users=users, active='users', calls=calls)
    Returns render_template('admin/users.html', users=users, active='users', title='Users', countries=COUNTRY_CODES)
    """
    # users = User.query.filter_by(_role_code=UserRole.tefl_pending.value)
    # calls = CallLog.query.filter_by(flagged=True)
    # return render_template('admin/index.html',
    #     users=users,
    #     active='users',
    #     calls=calls)
    users = User.query.all()
    return render_template('admin/users.html',
        users=users,
        active='users',
        title='Users',
        countries=COUNTRY_CODES)


@admin.route('/users')
@login_required
@admin_required
def users():
    """
    Get all users and user those to load admin/users/.
    The users view contains a table filled with details about all users in the system.

    Returns render_template('admin/users.html', users=users, active='users')

    """
    users = User.query.all()
    return render_template('admin/users.html',
        users=users,
        active='users',
        title='Users',
        countries=COUNTRY_CODES)


@admin.route('/user/<string:user_uid>', methods=['GET', 'POST'])
@login_required
@admin_required
def user(user_uid):
    """
    Allows the admin to change the following details about the user:

    - _role_code
    - status (_status_code)
    - created_time

    If the user does not exist, returns a 404.

    Returns render_template('admin/user.html')

    """
    user = User.query.filter_by(uid=user_uid).first_or_404()
    form = UserForm(obj=user, next=request.args.get('next'))

    if form.validate_on_submit():
        form.save(user)
        flash('User updated.', 'success')

    return render_template('admin/user.html',
        user=user,
        form=form,
        countries=COUNTRY_CODES)


@admin.route('/ban_user', methods=['POST'])
@login_required
@admin_required
def ban_user():
    """
    Bans a user
    """
    data = json.loads(request.data)
    uids = data['uids']

    if isinstance(uids, list):
        for user_uid in uids:
            ban(user_uid)
        time.sleep(0.75)
        return jsonify(flag='success', message='all users banned.')
    else:
        user_uid = uids
        ban(user_uid)
        time.sleep(0.75)
        return jsonify(flag='success', message='User ' + user_uid + ' was banned.')
    return jsonify(flag='error', message='invalid operation')


@admin.route('/tefl_users')
@login_required
@admin_required
def tefl_users():
    """
    Displays information about all TEFL users.
    Uses the same html as /users/ view
    """
    users = User.query.filter_by(_role_code=UserRole.tefl.value)
    return render_template('admin/users.html',
        users=users,
        active='users',
        title='TEFL Users',
        countries=COUNTRY_CODES)


@admin.route('/pending_tefl_users')
@login_required
@admin_required
def pending_tefl_users():
    """
    Displays information about all pending TEFL users.
    Uses the same html as /users/ view
    """

    users = User.query.filter_by(_role_code=UserRole.tefl_pending.value)
    return render_template('admin/pending_tefl_users.html', users=users, active='users')


@admin.route('/appr_tefl/<string:uid>/<int:code>')
@login_required
@admin_required
def appr_tefl(uid, code):
    """
    Args:
        id (int): id of user
        code (int): 0 is deny, 1 is approve

    Changes User._role_code for a given user in the db.
    """
    user = User().first(uid=uid)
    if code is 0:
        user.role = 'tefl_denied'
        db.session.add(user)
        db.session.commit()
    elif code is 1:
        user.role = 'tefl'
        db.session.add(user)
        db.session.commit()

    users = User.query.filter_by(_role_code=UserRole.tefl_pending.value)
    return render_template('admin/pending_tefl_users.html', users=users, active='users')


@admin.route('/translation/edit/<language>', methods=['POST', 'GET'])
@login_required
@admin_required
def edit_translation(language):
    """
    """
    form = EditTranslationForm(language=language)
    if form.validate_on_submit():
        file = request.files[form.file.name]
        if file:
            filename = secure_filename(file.filename)
            file.save(
                os.path.join(current_app.config['TRANSLATIONS_FOLDER'], language,
                    current_app.config['TRANSLATIONS_PATH'],
                    current_app.config['TRANSALTIONS_FILE']))
            os.system("pybabel compile -f -d theworldphone/translations")
            flash("Translation File has been uploaded")
            return redirect(url_for('admin.edit_translation', language=language))
    return render_template('admin/translation.html', form=form)


@admin.route('/translations', methods=['GET'])
@login_required
@admin_required
def translations():
    babel = Babel(current_app)
    languages = babel.list_translations()
    return render_template('admin/translations.html', languages=languages)


@admin.route('/translation/<language>', methods=['GET'])
@login_required
@admin_required
def existing_translation(language):
    return send_from_directory(os.path.join(
        current_app.config['TRANSLATIONS_FOLDER'],
        language,
        current_app.config['TRANSLATIONS_PATH']),
        current_app.config['TRANSALTIONS_FILE'])


@admin.route('/calls', methods=['GET'])
@login_required
@admin_required
def calls():
    """
    Get all calls and use those to load admin/calls/.
    The calls view contains a table filled with details about all calls in the system.

    return render_template('admin/calls.html', calls=calls)

theworldphone/modules/api/__init__.py
# -*- coding: utf-8 -*-

from .services import api

__all__ = [api]

theworldphone/modules/call/__init__.py
# -*- coding: utf-8 -*-
from .views import call
from .models import CallLog
from .constants import CALL_TYPES

__all__ = [call, CallLog, CALL_TYPES]

theworldphone/modules/frontend/__init__.py
# -*- coding: utf-8 -*-

from .views import frontend

__all__ = [frontend]

theworldphone/modules/mailchimp/__init__.py
# -*- coding: utf-8 -*-

from .services import chimp

__all__ = [chimp]

theworldphone/modules/redis/__init__.py
# -*- coding: utf-8 -*-

from redis_queue import RedisQueue
from redis_hash import RedisHash

__all__ = [RedisQueue, RedisHash]

theworldphone/modules/user/__init__.py
# -*- coding: utf-8 -*-

from .models import User
# from .views import user
from .services import user
from .constants import (USER_ROLE, ADMIN, USER, USER_STATUS, INACTIVE, ACTIVE, BANNED, TEFL_PENDING,
    TEFL, TEFL_DENIED, COUNTRY_CODES, LANGUAGES, TOPICS, GENDER_TYPE)

__all__ = [User, user, USER_ROLE, ADMIN, USER, USER_STATUS,
INACTIVE, ACTIVE, BANNED, TEFL_PENDING, TEFL, TEFL_DENIED, COUNTRY_CODES, LANGUAGES, TOPICS,
GENDER_TYPE]

theworldphone/modules/user/views.py
# -*- coding: utf-8 -*-
"""
    theworldphone.user.views
    ~~~~~~~~~~~~~~~~

    user views and controllers
"""

import json
from uuid import uuid4

from flask import (Blueprint, render_template, request, abort, flash, jsonify, url_for, redirect,
    Response)
from flask.ext.login import login_required, current_user
from flask.ext.babel import lazy_gettext as _

from theworldphone.extensions import db

from .constants import LANGUAGES, TEFL_PENDING, COUNTRY_CODES
from .models import User
from .forms import ProfileForm, PasswordForm


user = Blueprint('user', __name__, url_prefix='/user')


@user.route('/')
@user.route('/<int:offset>')
@login_required
def index(offset=0):
    """
    Creates a uuid4().hex room_id and returns

    render_template('user/index.html', user=current_user, languages=LANGUAGES, room_id=room_id)
    """
    room_id = uuid4().hex
    if current_user.is_authenticated and current_user.is_admin():
        return redirect(url_for('admin.index'))
    else:
        return render_template('user/index.html',
            user=current_user,
            languages=LANGUAGES,
            room_id=room_id)


@user.route('/details')
@login_required
def details(_id=None):
    """
    Returns details of a given user as a dictionary

    .. code-block:: javascript

        {
        'id': int,
        'name': str,
        'location': str,
        'gender': str,
        'overall': float,
        'tefl': bool
        }
    """
    if request.args.get('id'):
        user = User.get_by_id(request.args.get('id'))
        return jsonify(user.to_dict())
    abort(404)


@user.route('/request_tefl/<int:rtype>', methods=['POST'])
@login_required
def request_tefl(rtype):
    data = json.loads(request.data)

    if rtype == 0:
        user = User.get_by_id(int(data['id']))
        setattr(user, 'role_code', TEFL_PENDING)
        db.session.add(user)
        db.session.commit()

        flash("We'll be contacting you soon!", 'success')
    return jsonify({"status": "success"})


@user.route('/rate', methods=['POST'])
@login_required
def rate():
    data = json.loads(request.data)
    user = User.get_by_id(int(data['_id']))
    if user:
        _data = data['_data']
        user.set_ratings(_data)
        db.session.commit()
        return jsonify({'success': 'user vote recorded'})
    return Response(status=500, mimetype='application/json')


@user.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    """
    Return the user/profile view.
    Provides a form which allows the user to change their own

        - email
        - gender_code
        - source_langs
        - target_langs

    Validates form data & commits it to db.

    returns render_template('user/profile.html')
    """
    user = User.query.filter_by(name=current_user.name).first_or_404()
    form = ProfileForm(
        obj=user,
        email=current_user.email,
        role_code=current_user.role_code,
        status_code=current_user.status_code,
        next=request.args.get('next'))

    if form.validate_on_submit():
        form.create_profile(request, user)
        flash('Profile updated.', 'success')

    return render_template('user/profile.html',
        user=user,
        active="profile",
        form=form,
        countries=COUNTRY_CODES)


@user.route('/password', methods=['GET', 'POST'])
@login_required
def password():
    """
        Return the user/profile view.
        Provides a form which allows the user to change their own password
    """
    user = User.query.filter_by(name=current_user.name).first_or_404()
    form = PasswordForm(next=request.args.get('next'))

    if form.validate_on_submit():
        form.update_password(user)

        flash(_('Password updated.'), 'success')

    return render_template('user/password.html',
        user=user,
        active="password",
        form=form)

theworldphone/templates/user/index.html
{% set page_title = user.name %}
{% extends "layouts/base.html" %}

{% block js_top %}
<script type="text/javascript" src="//static.twilio.com/libs/twiliojs/1.2/twilio.min.js"></script>
{% endblock %}


{% block css_style %}
<link rel="stylesheet" href="{{ url_for('static', filename='vendor/flag-icon-css/css/flag-icon.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='vendor/bootstrap-select/dist/css/bootstrap-select.min.css') }}"/>
<link rel="stylesheet" href="{{ url_for('static', filename='vendor/bootstrap-multiselect/dist/css/bootstrap-multiselect.css') }}"/>
{% endblock %}


{% block body %}
<div class="container">
    <h3 class="page-header text-right" style="margin-bottom:0px;"><strong>{{_('Hello')}}, {{ user.name }}!</strong></h3>
    <h4 id="topic" class="text-right " style="margin-bottom:-20px;"></h4>

    <div id="call_window">
        {% include "call/partials/pre_call.html" %}
    </div>

    <div id="sketch-panel" class="panel panel-default hidden">
        <div class="panel-heading">Draw Something</div>
        <div class="panel-body">
            <div class="btn-group btn-group-justified" style="margin-right: auto; margin-top: 10px; width: 100%;"> 
              <a class="btn btn-info color-picker upper-button">Blue</a>          
              <a class="btn btn-success color-picker">Green</a>
              <a class="btn btn-warning color-picker">Yellow</a>
              <a class="btn btn-danger color-picker">Red</a>
              <a class="btn btn-success color-picker black-pick upper-button" style="border-bottom-width: 0px;">Black</a>
            </div>
            <div class="clearfix"></div>
            <!-- <div id="sketchContainer" style="width: 100%; border: 1px solid rgba(0, 0, 0, 0.2); width: 100%;"> -->
            <div id="sketchContainer" style="width: 100%; height: 300px; border: 1px solid rgba(0,0,0,0.2)"><canvas id="sketch"></canvas></div>
                <!-- <canvas id="sketch" style="min-width:300px; min-height:300px; position: relative; width:100%;"></canvas> -->
                <div class="btn-group btn-group-justified" style="margin-right: auto; width: 100%;"> 
                    <a class="btn btn-info user-color-pick bottom-button" style="width: 30%;">User Color</a>
                    <a class="btn btn-success plus-size" style="width: 15%;">
                      <i class="fa fa-plus-square"></i>
                    </a>
                    <a class="btn btn-warning clear" style="width: 15%;">
                      <i class="fa fa-times-circle"></i>
                    </a>
                    <a class="btn btn-danger minus-size" style="width: 15%;">
                      <i class="fa fa-minus-square"></i>
                    </a>
                    <a class="btn btn-default eraser bottom-button" style="width: 35%; border-top-width: 0px;">
                      <i class="fa fa-eraser"></i>
                    </a>
                </div>
            </div>
      </div>
    </div>

</div>
{% endblock %}


{% block extra_js %}
<script type="text/javascript" src="{{ url_for('static', filename='vendor/bootstrap-select/dist/js/bootstrap-select.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='vendor/bootstrap-multiselect/dist/js/bootstrap-multiselect.js') }}"></script>
<link href="{{ url_for('static', filename='vendor/bootstrap-star-rating/css/star-rating.min.css') }}" media="all" rel="stylesheet" type="text/css" />
<script src="{{ url_for('static', filename='vendor/bootstrap-star-rating/js/star-rating.min.js') }}"></script>

<script>

    $("input.rating").rating({ min:0, max:5, step:0.5, size:'xs', showClear:false, showCaption:false});

    $('select.multiselect').multiselect({
      buttonWidth: '100%',
      nonSelectedText: 'Select at least one',
    });

    var session = null;
    var call_type, lang1, lang2, topic_lang;

    function wait(time) {
        wait_time = setTimeout(function(){
            $.get("{{ url_for('call.no_match') }}", function(data){
                $('#call_window').html(data.html);
            });
        }, time);
    }

    function paired() {
        clearTimeout(wait_time);
    }

    $(document).on('change', '#exchange_slang', function() {
        var selected = $(this).val();
        if (selected[0] == selected[1])
            $('#xchg_warn').removeClass('hidden');
        else
            $('#xchg_warn').addClass('hidden');
    });

    $(document).on('click', '#exchange', function(){
        call_type = 0;
        lang1 = $('#exchange_slang').val()[0];
        lang2 = $('#exchange_slang').val()[1];

        var data = {'room_id': '{{room_id}}', 'call_type': 0,  'slang': parseInt($('#exchange_slang').val()[0]),
            'tlang': parseInt($('#exchange_slang').val()[1]), 'user_type': 0}
        $.ajax({
            url: "{{ url_for('call.make_call') }}",
            data: JSON.stringify(data),
            contentType: 'application/json',
            async: false,
            cache: false,
            type: 'POST',
            success: function (result) {
                $('#call_window').html(result.html);
                if (result.stat == 0){
                    wait(7000);
                }
                else {
                    call(result);
                }
            }
        });
    });

    $(document).on('click', '#random', function(){

        call_type = 1;
        topic_lang = $('#random_lang option:selected').text()
        lang1 = $('#random_lang').val();
        lang2 = '';

        var data = {'room_id': '{{room_id}}', 'call_type': 1, 'call_lang': parseInt($('#random_lang').val()), 'user_type': 0}
        $.ajax({
            url: "{{ url_for('call.make_call') }}",
            data: JSON.stringify(data),
            contentType: 'application/json',
            async: false,
            cache: false,
            type: 'POST',
            success: function (result) {
                $('#call_window').html(result.html);

                if (result.stat == 0){
                    wait(7000);
                }
                else {
                    call(result);
                }
            }
        });
    });

    $(document).on('click', '#tefl_s', function(){
        call_type = 2;
        lang1 = '';
        lang2 = '';

        var data = {'room_id': '{{room_id}}', 'call_type': 2, 'user_type': 1}
        $.ajax({
            url: "{{ url_for('call.make_call') }}",
            data: JSON.stringify(data),
            contentType: 'application/json',
            async: false,
            cache: false,
            type: 'POST',
            success: function (result) {
                $('#call_window').html(result.html);
                if (result.stat == 0){
                    wait(7000);
                }
                else {
                    call(result);
                }
            }
        });
    });

    $(document).on('click', '#tefl_i', function(){
        call_type = 2;
        lang1 = '';
        lang2 = '';

        var data = {'room_id': '{{room_id}}', 'call_type': 2, 'user_type': 2}
        $.ajax({
            url: "{{ url_for('call.make_call') }}",
            data: JSON.stringify(data),
            contentType: 'application/json',
            async: false,
            cache: false,
            type: 'POST',
            success: function (result) {
                $('#call_window').html(result.html);
                if (result.stat == 0){
                    wait(10000);
                }
                else {
                    call(result);
                }
            }
        });
    });

    $(document).on('click', '#hangup_button', function(){
        session.close();
    });
    $(document).on('click', '#home_button', function(){
        session.close();
    });

    $(document).ready(function() {
        $('select.selectpicker').selectpicker({
            dropupAuto: false
        });
        $('.bootstrap-select.btn-group .dropdown-menu li a').on('click', function(event) {
            if (! $(this).closest('div.btn-group.bootstrap-select').hasClass('open'))
                event.stopPropagation();
        });

    });

</script>
{% endblock %}

theworldphone/templates/user/password.html
{% from "macros/_form.html" import render_form %}

{% extends 'user/layout.html' %}

{% block body %}

  <style type="text/css">
    input#submit {
      margin-top: 10px;
    }
  </style>

    <div class="row">
      <h3>&nbsp;</h3>
        <div class="col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">

          <div class="panel panel-default">
              <div class="panel-heading">
                  <h1 class="panel-title">{{_('Change Password')}}</h1>
              </div>
              <div class="panel-body">
                <div>
                  {{ render_form(url_for('user.password'), form) }}
                </div>
              </div>
          </div>

        </div>
    </div>
{% endblock %}

theworldphone/templates/user/profile.html
{% from "macros/_form.html" import render_field, render_checkbox %}
{% extends 'frontend/layout.html' %}

{% set page_title = 'Update Profile' %}


{% block body %}
<div class="row">
  <h3>&nbsp;</h3>

  {% if user.is_admin() %}
  <div class="col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3">
    <div class="panel panel-default">
        <div class="panel-heading">
          <h1 class="panel-title">{{user.name}}'s {{_('Profile')}}</h1>
        </div>

        <div class="panel-body">
          <form method="POST">
            {{ form.csrf_token }}
            {{ render_field(form.email, class="form-control") }}
            {{ render_field(form.gender_code, class="form-control") }}
            <button type="submit" id="submit" class="btn btn-lg btn-info btn-block">{{_('Save')}}</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  {% else %}
  <div class="col-sm-6 col-sm-offset-1 col-md-offset-2 col-md-5">

    <div class="panel panel-default">
      <div class="panel-heading">
        <h1 class="panel-title">{{user.name}}'s {{_('Profile')}}</h1>
      </div>

      <div class="panel-body">
        <form method="POST">
          {{ form.csrf_token }}
          {{ render_field(form.email, class="form-control") }}
          {{ render_field(form.gender_code, class="form-control") }}

          <label class="control-label">I live in...</label>
          <label class="pull-right">
            <strong>{{ countries[user.location] }}</strong>
            <input class="form-control" id="location" name="location" type="hidden" value="{{user.location}}">
            <span class="flag-icon flag-icon-{{ user.location|lower }}"></span>
          </label>
          <br><br>

          {{ render_field(form.source_langs, id="native-language", multiple="multiple") }}
          {{ render_field(form.target_langs, id="target-language", multiple="multiple") }}

          <br>

          <button type="submit" id="submit" class="btn btn-lg btn-info btn-block">{{_('Save')}}</button>

        </form>
        <hr>
        <span><a href="{{ url_for('user.password') }}">Change Password</a></span>
      </div>

      {% if user.no_tefl() %}
      <div class="panel-footer panel-default text-right">
        <a id="request_tefl">{{_('Request TEFL status?')}}</a>
      </div>
      {% elif user.is_tefl_pending() %}
      <div class="panel-footer panel-default text-right disabled">
        {{_('Your TEFL request is pending.')}}
      </div>
      {% elif user.tefl_denied() %}
      <div class="panel-footer panel-default text-right disabled">
        {{_('Your TEFL request was denied.')}}
      </div>
      {% else %}
      <div class="panel-footer panel-default text-right disabled">
        {{_("Congrats! You're a TEFL instructor.")}}
      </div>
      {% endif %}
    </div>
  </div>

  <div class="col-sm-4 col-md-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1 class="panel-title">{{_('My Ratings')}}</h1>
      </div>

      <div class="panel-body">
        <form class="form-inline">
        <fieldset>
          <label class="control-label"><strong>Vocabulary</strong></label>
          <input name="vocabulary" type="number" class="rating input-mini" value="{{ current_user.get_ratings['vocabulary'] }}">

          <br>
          <label class="control-label"><strong>Accent</strong></label>
          <input name="accent" type="number" class="rating input-mini" value="{{ current_user.get_ratings['accent'] }}">

          <br>
          <label class="control-label"><strong>Grammar</strong></label>
          <input name="grammar" type="number" class="rating input-mini" value="{{ current_user.get_ratings['grammar'] }}">

          <br>
          <label class="control-label"><strong>Skill</strong></label>
          <input name="skill" type="number" class="rating input-mini" value="{{ current_user.get_ratings['skill'] }}">

          {% if user.is_tefl() %}
          <br>
          <label class="control-label"><strong>Ability</strong></label>
          <input name="ability" type="number" class="rating input-mini" value="{{ current_user.get_ratings['ability'] }}">

          <br>
          <label class="control-label"><strong>Clarity</strong></label>
          <input name="clarity" type="number" class="rating input-mini" value="{{ current_user.get_ratings['clarity'] }}">
          {% endif %}
        </fieldset>
        </form>
      </div>

      <div class="panel-footer">
        <strong>Overall:</strong>
        <span class="pull-right" style="margin-top: -12px;">
          <input name="overall" type="number" class="rating" value="{{ current_user.overall_rating }}">
        </span>
      </div>

    </div>
  </div>
  {% endif %}
</div>

{% endblock %}

{% block css_style %}
<link rel="stylesheet" href="{{ url_for('static', filename='vendor/flag-icon-css/css/flag-icon.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='vendor/bootstrap-star-rating/css/star-rating.min.css') }}" media="all" type="text/css" />
<link rel="stylesheet" href="{{ url_for('static', filename='vendor/bootstrap-multiselect/dist/css/bootstrap-multiselect.css') }}"/>
<style type="text/css">
  body {
    background-color: #fff;
  }
</style>
{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="{{ url_for('static', filename='vendor/bootstrap-multiselect/dist/js/bootstrap-multiselect.js') }}"></script>
<script>
$(document).ready(function() {
        $('#native-language').multiselect({
            buttonWidth: '100%',
            nonSelectedText: 'Select at least one',
            templates: {

            }
        });

        $('#target-language').multiselect({
            buttonWidth: '100%',
            nonSelectedText: 'Select at least one',
            templates: {

            }
        });

        $(document).on('click', '#request_tefl', function(){
            var data = {'id': '{{user.id}}'}
            $.ajax({
                url: "{{ url_for('user.request_tefl', rtype=0) }}",
                data: JSON.stringify(data),
                contentType: 'application/json',
                async: false,
                type: 'POST'
            });
            location.reload()
        });
    });
</script>

<script src="{{ url_for('static', filename='vendor/bootstrap-star-rating/js/star-rating.min.js') }}"></script>

<script>
    $("input.rating").rating({ min:0, max:5, step:0.5, size:'xs', showClear:false, showCaption:false, disabled:true});
</script>
{% endblock %}