theworldphone/modules/admin/forms.py
# -*- coding: utf-8 -*-
"""
    theworldphone.modules.admin.forms
    ~~~~~~~~~~~~~~~~

    admin module forms
"""

from flask.ext.wtf import Form
from wtforms import (HiddenField, SubmitField, SelectField, FileField, DateField)
from wtforms.validators import AnyOf

from theworldphone.extensions import db
from theworldphone.modules.user.constants import UserStatus


class UserForm(Form):
    next = HiddenField()
    status = SelectField(u"Status", [AnyOf([str(s.name) for s in UserStatus])],
            choices=[(str(s.name), s.name.capitalize()) for s in UserStatus])
    created_time = DateField(u'Created time')  # _created_at ?
    submit = SubmitField(u'Save')

    def save(self, user):
        self.populate_obj(user)
        db.session.add(user)
        db.session.commit()


class EditTranslationForm(Form):
    multipart = True
    file = FileField(u"Upload Translation File")
    language = HiddenField()
    submit = SubmitField(u'Save')

theworldphone/__init__.py
# -*- coding: utf-8 -*-

from factory import create_app

theworldphone/modules/admin/__init__.py
# -*- coding: utf-8 -*-

from .views import admin

__all__ = [admin]

theworldphone/modules/admin/views.py
# -*- coding: utf-8 -*-
"""
    theworldphone.modules.admin.views
    ~~~~~~~~~~~~~~~~

    admin module views and controllers
"""

from werkzeug import secure_filename
import os, json, urllib, re, requests, time, datetime

from itertools import chain

from flask import (Blueprint, render_template, request, flash, current_app, send_from_directory,
    redirect, url_for, jsonify, abort)
from flask.ext.login import login_required, login_user, logout_user, current_user
from flask.ext.babel import Babel

from theworldphone.extensions import db
from theworldphone.decorators import admin_required

from theworldphone.modules.frontend.forms import LoginForm
from theworldphone.modules.redis import RedisQueue
from theworldphone.modules.user.models import User, Language
from theworldphone.modules.user.constants import UserRole, COUNTRY_CODES
from theworldphone.modules.call import CallLog
from theworldphone.modules.call.constants import CallType

from .forms import UserForm, EditTranslationForm

admin = Blueprint('admin', __name__, url_prefix='/admin')


# flash(_( -> flash((

@admin.route('/login', methods=['GET', 'POST'])
def login():
    '''
    If user is not logged in:

    1) Show the user the login form.
    2) Handle the input form the login form.

    If user is already logged, send them to user.index or admin.index as appropriate

    If User.authenticate(form.login.data, form.password.data) checks out
    send them to user.index or admin.index as appropriate.

    If the user is banned, flash a message and reshow login form.

    '''
    if current_user.is_authenticated and not current_user.is_admin():
        return redirect(url_for('user.index'))
    elif current_user.is_authenticated and current_user.is_admin():
        return redirect(url_for('admin.index'))

    form = LoginForm(login=request.args.get('login', None),
                     next=request.args.get('next', None))

    if form.validate_on_submit():
        user, authenticated = User.authenticate(form.login.data,
                                    form.password.data)
        if user and authenticated and user.status == 'banned':
            flash(('Sorry, you are not allowed access to your account due to inappropriate behavior.'), 'danger')
        elif user and authenticated and user.status == 'active':
            remember = request.form.get('remember') == 'y'
            if login_user(user, remember=remember):

                if request.environ.get('HTTP_X_REAL_IP', request.remote_addr) not in user._ip_list.values():
                    user._ip_list[datetime.datetime.now()] = request.environ.get('HTTP_X_REAL_IP', request.remote_addr)
                    db.session.commit()

                flash(("Logged in"), 'success')
            if user.is_admin():
                return redirect(url_for('admin.index'))
            else:
                return redirect(form.next.data or url_for('user.index'))
        else:
            flash(('Sorry, invalid login'), 'danger')

    return render_template('frontend/login.html', form=form)


@admin.route('/reauth', methods=['GET', 'POST'])
@login_required
def reauth():
    '''This function allows a user to attempt to log in
    again after a failed attempt.

    **Returns:**
        - Change password view on reauthentication success
        - Reauthentication view on reauthentication failure.

    '''
    form = ReauthForm(next=request.args.get('next'))

    if request.method == 'POST':
        user, authenticated = User.authenticate(current_user.name,
                                    form.password.data)
        if user and authenticated:
            confirm_login()
            current_app.logger.debug('reauth: %s' % session['_fresh'])
            flash(('Reauthenticated.'), 'success')
            return redirect('/change_password')

        flash(('Password is wrong.'), 'danger')
    return render_template('frontend/reauth.html', form=form)


@admin.route('/logout')
@login_required
def logout():
    '''This function logs user out of current session.

    Returns:
        Redirects to login view on success.

    '''
    logout_user()
    flash(('Logged out'), 'success')
    return redirect(url_for('admin.login'))


@admin.route('/')
@login_required
@admin_required
def index():
    """
    # Grab TEFL_PENDING users and flagged calls.
    Grab all users.
    Use those to load admin index page.

    # Returns render_template('admin/index.html', users=users, active='users', calls=calls)
    Returns render_template('admin/users.html', users=users, active='users', title='Users', countries=COUNTRY_CODES)
    """
    # users = User.query.filter_by(_role_code=UserRole.tefl_pending.value)
    # calls = CallLog.query.filter_by(flagged=True)
    # return render_template('admin/index.html',
    #     users=users,
    #     active='users',
    #     calls=calls)
    users = User.query.all()
    return render_template('admin/users.html',
        users=users,
        active='users',
        title='Users',
        countries=COUNTRY_CODES)


@admin.route('/users')
@login_required
@admin_required
def users():
    """
    Get all users and user those to load admin/users/.
    The users view contains a table filled with details about all users in the system.

    Returns render_template('admin/users.html', users=users, active='users')

    """
    users = User.query.all()
    return render_template('admin/users.html',
        users=users,
        active='users',
        title='Users',
        countries=COUNTRY_CODES)


@admin.route('/user/<string:user_uid>', methods=['GET', 'POST'])
@login_required
@admin_required
def user(user_uid):
    """
    Allows the admin to change the following details about the user:

    - _role_code
    - status (_status_code)
    - created_time

    If the user does not exist, returns a 404.

    Returns render_template('admin/user.html')

    """
    user = User.query.filter_by(uid=user_uid).first_or_404()
    form = UserForm(obj=user, next=request.args.get('next'))

    if form.validate_on_submit():
        form.save(user)
        flash('User updated.', 'success')

    return render_template('admin/user.html',
        user=user,
        form=form,
        countries=COUNTRY_CODES)


@admin.route('/ban_user', methods=['POST'])
@login_required
@admin_required
def ban_user():
    """
    Bans a user
    """
    data = json.loads(request.data)
    uids = data['uids']

    if isinstance(uids, list):
        for user_uid in uids:
            ban(user_uid)
        time.sleep(0.75)
        return jsonify(flag='success', message='all users banned.')
    else:
        user_uid = uids
        ban(user_uid)
        time.sleep(0.75)
        return jsonify(flag='success', message='User ' + user_uid + ' was banned.')
    return jsonify(flag='error', message='invalid operation')


@admin.route('/tefl_users')
@login_required
@admin_required
def tefl_users():
    """
    Displays information about all TEFL users.
    Uses the same html as /users/ view
    """
    users = User.query.filter_by(_role_code=UserRole.tefl.value)
    return render_template('admin/users.html',
        users=users,
        active='users',
        title='TEFL Users',
        countries=COUNTRY_CODES)


@admin.route('/pending_tefl_users')
@login_required
@admin_required
def pending_tefl_users():
    """
    Displays information about all pending TEFL users.
    Uses the same html as /users/ view
    """

    users = User.query.filter_by(_role_code=UserRole.tefl_pending.value)
    return render_template('admin/pending_tefl_users.html', users=users, active='users')


@admin.route('/appr_tefl/<string:uid>/<int:code>')
@login_required
@admin_required
def appr_tefl(uid, code):
    """
    Args:
        id (int): id of user
        code (int): 0 is deny, 1 is approve

    Changes User._role_code for a given user in the db.
    """
    user = User().first(uid=uid)
    if code is 0:
        user.role = 'tefl_denied'
        db.session.add(user)
        db.session.commit()
    elif code is 1:
        user.role = 'tefl'
        db.session.add(user)
        db.session.commit()

    users = User.query.filter_by(_role_code=UserRole.tefl_pending.value)
    return render_template('admin/pending_tefl_users.html', users=users, active='users')


@admin.route('/translation/edit/<language>', methods=['POST', 'GET'])
@login_required
@admin_required
def edit_translation(language):
    """
    """
    form = EditTranslationForm(language=language)
    if form.validate_on_submit():
        file = request.files[form.file.name]
        if file:
            filename = secure_filename(file.filename)
            file.save(
                os.path.join(current_app.config['TRANSLATIONS_FOLDER'], language,
                    current_app.config['TRANSLATIONS_PATH'],
                    current_app.config['TRANSALTIONS_FILE']))
            os.system("pybabel compile -f -d theworldphone/translations")
            flash("Translation File has been uploaded")
            return redirect(url_for('admin.edit_translation', language=language))
    return render_template('admin/translation.html', form=form)


@admin.route('/translations', methods=['GET'])
@login_required
@admin_required
def translations():
    babel = Babel(current_app)
    languages = babel.list_translations()
    return render_template('admin/translations.html', languages=languages)


@admin.route('/translation/<language>', methods=['GET'])
@login_required
@admin_required
def existing_translation(language):
    return send_from_directory(os.path.join(
        current_app.config['TRANSLATIONS_FOLDER'],
        language,
        current_app.config['TRANSLATIONS_PATH']),
        current_app.config['TRANSALTIONS_FILE'])


@admin.route('/calls', methods=['GET'])
@login_required
@admin_required
def calls():
    """
    Get all calls and use those to load admin/calls/.
    The calls view contains a table filled with details about all calls in the system.

    return render_template('admin/calls.html', calls=calls)

theworldphone/modules/api/__init__.py
# -*- coding: utf-8 -*-

from .services import api

__all__ = [api]

theworldphone/modules/call/__init__.py
# -*- coding: utf-8 -*-
from .views import call
from .models import CallLog
from .constants import CALL_TYPES

__all__ = [call, CallLog, CALL_TYPES]

theworldphone/modules/frontend/__init__.py
# -*- coding: utf-8 -*-

from .views import frontend

__all__ = [frontend]

theworldphone/modules/mailchimp/__init__.py
# -*- coding: utf-8 -*-

from .services import chimp

__all__ = [chimp]

theworldphone/modules/redis/__init__.py
# -*- coding: utf-8 -*-

from redis_queue import RedisQueue
from redis_hash import RedisHash

__all__ = [RedisQueue, RedisHash]

theworldphone/modules/user/__init__.py
# -*- coding: utf-8 -*-

from .models import User
# from .views import user
from .services import user
from .constants import (USER_ROLE, ADMIN, USER, USER_STATUS, INACTIVE, ACTIVE, BANNED, TEFL_PENDING,
    TEFL, TEFL_DENIED, COUNTRY_CODES, LANGUAGES, TOPICS, GENDER_TYPE)

__all__ = [User, user, USER_ROLE, ADMIN, USER, USER_STATUS,
INACTIVE, ACTIVE, BANNED, TEFL_PENDING, TEFL, TEFL_DENIED, COUNTRY_CODES, LANGUAGES, TOPICS,
GENDER_TYPE]

theworldphone/modules/user/views.py
# -*- coding: utf-8 -*-
"""
    theworldphone.user.views
    ~~~~~~~~~~~~~~~~

    user views and controllers
"""

import json
from uuid import uuid4

from flask import (Blueprint, render_template, request, abort, flash, jsonify, url_for, redirect,
    Response)
from flask.ext.login import login_required, current_user
from flask.ext.babel import lazy_gettext as _

from theworldphone.extensions import db

from .constants import LANGUAGES, TEFL_PENDING, COUNTRY_CODES
from .models import User
from .forms import ProfileForm, PasswordForm


user = Blueprint('user', __name__, url_prefix='/user')


@user.route('/')
@user.route('/<int:offset>')
@login_required
def index(offset=0):
    """
    Creates a uuid4().hex room_id and returns

    render_template('user/index.html', user=current_user, languages=LANGUAGES, room_id=room_id)
    """
    room_id = uuid4().hex
    if current_user.is_authenticated and current_user.is_admin():
        return redirect(url_for('admin.index'))
    else:
        return render_template('user/index.html',
            user=current_user,
            languages=LANGUAGES,
            room_id=room_id)


@user.route('/details')
@login_required
def details(_id=None):
    """
    Returns details of a given user as a dictionary

    .. code-block:: javascript

        {
        'id': int,
        'name': str,
        'location': str,
        'gender': str,
        'overall': float,
        'tefl': bool
        }
    """
    if request.args.get('id'):
        user = User.get_by_id(request.args.get('id'))
        return jsonify(user.to_dict())
    abort(404)


@user.route('/request_tefl/<int:rtype>', methods=['POST'])
@login_required
def request_tefl(rtype):
    data = json.loads(request.data)

    if rtype == 0:
        user = User.get_by_id(int(data['id']))
        setattr(user, 'role_code', TEFL_PENDING)
        db.session.add(user)
        db.session.commit()

        flash("We'll be contacting you soon!", 'success')
    return jsonify({"status": "success"})


@user.route('/rate', methods=['POST'])
@login_required
def rate():
    data = json.loads(request.data)
    user = User.get_by_id(int(data['_id']))
    if user:
        _data = data['_data']
        user.set_ratings(_data)
        db.session.commit()
        return jsonify({'success': 'user vote recorded'})
    return Response(status=500, mimetype='application/json')


@user.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    """
    Return the user/profile view.
    Provides a form which allows the user to change their own

        - email
        - gender_code
        - source_langs
        - target_langs

    Validates form data & commits it to db.

    returns render_template('user/profile.html')
    """
    user = User.query.filter_by(name=current_user.name).first_or_404()
    form = ProfileForm(
        obj=user,
        email=current_user.email,
        role_code=current_user.role_code,
        status_code=current_user.status_code,
        next=request.args.get('next'))

    if form.validate_on_submit():
        form.create_profile(request, user)
        flash('Profile updated.', 'success')

    return render_template('user/profile.html',
        user=user,
        active="profile",
        form=form,
        countries=COUNTRY_CODES)


@user.route('/password', methods=['GET', 'POST'])
@login_required
def password():
    """
        Return the user/profile view.
        Provides a form which allows the user to change their own password
    """
    user = User.query.filter_by(name=current_user.name).first_or_404()
    form = PasswordForm(next=request.args.get('next'))

    if form.validate_on_submit():
        form.update_password(user)

        flash(_('Password updated.'), 'success')

    return render_template('user/password.html',
        user=user,
        active="password",
        form=form)

theworldphone/templates/call/partials/in_call.html
<script>
  var TogetherJSConfig_findRoom = "{{room_id}}";
  var TogetherJSConfig_dontShowClicks = true;
  var TogetherJSConfig_ignoreForms = true;
  var TogetherJSConfig_disableSessionLoad = true;
</script>
<script src="http://tjs.theworldphone.com/togetherjs-min.js"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/whiteboard.js') }}"></script>

<script>
    var session = null;
    Twilio.Device.setup("{{ token }}");

    Twilio.Device.error(function (error) {
        $("#blurb").text("Error: " + error.message);
        $("#hangup_button").prop("disabled", true);
        $("#home_button").removeClass('hidden');
        session.close();
    });

    Twilio.Device.connect(function (conn) {
        $("#sketch-panel").removeClass('hidden');
        $("#blurb").text("Say hello to {{partner.name}}!");
        $("#hangup_button").removeClass('hidden');

        if (call_type == 1) {
          var topics = {{ topics|safe }};
          var topic = {{ topic }};
          items = topics[topic_lang];
          $('#topic').append('&nbsp;');
          $topic = $('#topic');
          $topic.slideDown();

          $topic.text( decodeURIComponent(escape(items['{{topic}}'])) );
        }

        whiteboard();
        TogetherJS(this);
        TogetherJS.on("ready", function(){
          session = TogetherJS.require('session');
        });
        TogetherJS.reinitialize();

    });

    Twilio.Device.disconnect(function (conn) {
        $("#blurb").text("We hope you enjoyed your call!");
        $("#hangup_button").prop("disabled", true);
        $("#home_button").removeClass('hidden');
        $("#sketch-panel").addClass('hidden');
        $("input.rating").rating('refresh', { min:0, max:5, step:0.5, size:'xs', showClear:false, showCaption:false});
        $('select.multiselect').multiselect('refresh');
        $("#ratingContainer").removeClass('hidden');

        session.close();

        if (conn.parameters.CallSid) {
          var data = {'call_sid': conn.parameters.CallSid, 'caller_id': '{{current_user.id}}',
              'caller_username': '{{current_user.name}}', 'callee_id': '{{partner.id}}',
              'callee_username': '{{partner.name}}', 'call_type': call_type, 'lang1': lang1, 'lang2': lang2,
              'ips': ["{{ips[0]}}", "{{ips[1]}}"], 'locs': ["{{locs[0]}}", "{{locs[1]}}"], 'room_id': '{{ room_id }}'  }
          $.ajax({
              url: "{{ url_for('call.save') }}",
              data: JSON.stringify(data),
              contentType: 'application/json',
              type: 'POST'
          })
        }
        else if (conn.parameters.CallSid) {
          var data = {'caller_id': '{{current_user.id}}', 'callee_id': '{{partner.id}}',
              'locs': '{{locs}}[0]'}

          $.ajax({
              url: "{{ url_for('call.save') }}",
              data: JSON.stringify(data),
              contentType: 'application/json',
              type: 'POST',
          });
        }
    });

    function call(data) {
        // get the phone number or client to connect the call to
        params = {"PhoneNumber": '{{partner.name}}', "From": '{{current_user.id}}'};
        Twilio.Device.connect(params);
    }

    function hangup() {
        Twilio.Device.disconnectAll();
    }


  /* Rate Partner
     - package the rating data and partner ID
     - POST to the user rating endpoint
     - Hide when complete
  */
  $(document).on('click', '#rate_caller', function () {
      var _data = {};
      $('input.rating').each( function() {
          _data[$(this).attr('name')] = $(this).val();
      });
      var data = {
        '_data': _data,
        '_id': '{{ partner.id }}'
      };
      $.ajax({
          url: "{{ url_for('user.rate') }}",
          data: JSON.stringify(data),
          contentType: 'application/json',
          async: false,
          type: 'POST',
          success: function(data) {
              var text = '<strong>Thank you for rating your partner! Your input is what makes The Worldphone work!</strong>';
              $('.rate-hide').addClass('hidden');
              $('#rate-call-feedback').removeClass('hidden');
              $('#rate-call-feedback .panel-body').html(text);
          }
      });
      return false;
  });

  /* Report Caller
     -
     - POST to the calls.flag endpoint
  */
  $(document).on('click', '#report_caller', function () {

      var _data = {};
      _data['room_id'] = '{{ room_id }}'
      _data['reporter_id'] = '{{ current_user.id }}'
      _data['reported_id'] = '{{ partner.id }}'
      _data['reported_name'] = '{{ partner.name }}'
      _data['comment'] = $("[name='flag-comments']").val();
      _data['flags'] = $("[name='flag-type']").val();

      var data = {
        '_data': _data,
      };
      $.ajax({
          url: "{{ url_for('call.flag') }}",
          data: JSON.stringify(data),
          contentType: 'application/json',
          async: false,
          type: 'POST',
          success: function(data) {
              $('#collapseOne .panel-body').html('<strong>Thank you, a report has been sent.</strong>');
          }
      });
      return false;
  });

</script>

<br>
<h3 id="blurb">HEY. You started a call. You're going to talk to {{partner.name}}.</h3>
<br><br>

<button id="hangup_button" class="btn btn-danger hidden" onclick="hangup();">
    Hangup
</button>

<a id="home_button" class="btn btn-warning hidden" href="{{ url_for('user.index') }}">
    Make a new call!
</a>

<br><br>

<div id="ratingContainer" class="hidden">
  <div class="col-lg-12 well" style="margin-bottom:80px;">
      {% include 'call/partials/rate_call.html' %}
  </div>
</div>

theworldphone/templates/call/partials/no_match.html
<br>
<h3 id="blurb">There isn't anyone online for you to talk to.<br>Try again!</h3>
<br><br>

<a id="home_button" class="btn btn-warning" href="{{ url_for('user.index') }}">
    Make a new call!
</a>

<br><br>

theworldphone/templates/call/partials/pre_call.html
<section class="price-1">
  <h3><strong>Make a call.</strong></h3>
  <br>
  <div class="row plans">
      <div class="col-sm-4">
          <div class="plan">
              <div class="title" style="border-bottom:3px solid #ebedee;;margin-bottom:20px;">Exchange</div>
              <a id="exchange" class="btn btn-info call">Make A Call</a>
              <br><br>

              <select id="exchange_slang" class="selectpicker" multiple data-size="4" data-dropup-auto=false title='Select Languages'>
                <optgroup label="Your Language" data-max-options="1">
                {% for l in languages %}
                  <option value="{{ l }}">{{ languages[l] }}</option>
                {% endfor %}
                </optgroup>
                <optgroup label="Their Language" data-max-options="1">
                {% for l in languages %}
                  <option value="{{ l }}">{{ languages[l] }}</option>
                {% endfor %}
                </optgroup>
              </select>

              <p id="xchg_warn" class="help-block text-danger hidden">
                You must choose two different languages.
              </p>

              <br>
          </div>
      </div>

      <div class="col-sm-4">
          <div class="plan middle-plan">
              <div class="title" style="border-bottom:3px solid #ebedee;;margin-bottom:20px;">Random</div>
              <a id="random" class="btn btn-info" href="#">Make A Call</a>
              <br><br>
              <div class="center-block">
              <select id="random_lang" class="selectpicker" data-size="4" data-dropup-auto=false>
                <option value="" disabled selected style='display:none;'>Select Language</option>
                {% for l in languages %}
                  <option value="{{ l }}">{{ languages[l] }}</option>
                {% endfor %}
              </select>
              </div>
              <br><br>
            </div>
      </div>

      <div class="col-sm-4">
          <div class="plan">
              <div class="title" style="border-bottom:3px solid #ebedee;;margin-bottom:20px;">TEFL</div>
              <a id="tefl_s" class="btn btn-info" href="#">Make A Call As Student</a>
              {% if user.is_tefl() %}
              <br><br>
              <a id="tefl_i" class="btn btn-info" href="#">Make A Call As Instructor</a>
              {% endif %}
          </div>
      </div>
  </div>
</section>

theworldphone/templates/call/partials/waiting_call.html
<script>
  var TogetherJSConfig_findRoom = "{{room_id}}"
  var TogetherJSConfig_dontShowClicks = true;
  var TogetherJSConfig_ignoreForms = true;
  var TogetherJSConfig_disableSessionLoad = true;
</script>
<script src="http://tjs.theworldphone.com/togetherjs-min.js"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/whiteboard.js') }}"></script>

<script>

  var partner;
  var details_url = "{{ url_for('user.details') }}?id=";
  var session = null;

  Twilio.Device.setup("{{ token }}");

  Twilio.Device.error(function (error) {
      $("#blurb").text("Error: " + error.message);
      $("#hangup_button").prop("disabled", true);
      $("#home_button").removeClass('hidden');
      session.close();
  });

  Twilio.Device.disconnect(function (conn) {
      $("#blurb").text("We hope you enjoyed your call!");
      $("#hangup_button").prop("disabled", true);
      $("#home_button").removeClass('hidden');
      $("input.rating").rating('refresh', { min:0, max:5, step:0.5, size:'xs', showClear:false, showCaption:false});
      $('select.multiselect').multiselect('refresh');
      $("#ratingContainer").removeClass('hidden');
      $("#sketch-panel").addClass('hidden');

      session.close();
  });

  Twilio.Device.incoming(function (conn) {
      paired();
      $("#hangup_button").removeClass('hidden');
      $("#sketch-panel").removeClass('hidden');

      $.ajax({
          url: details_url+conn.parameters.From,
          async: false,
          success: function(data){
              partner = data;
          }
      });

      $("#blurb").text("Say hello to " + partner.name + '!');


      if (call_type == 1) {
        var topics = {{ topics|safe }};
        var topic = {{ topic }};
        items = topics[topic_lang];
        $('#topic').append('&nbsp;');
        $topic = $('#topic');
        $topic.slideDown();
        $topic.text( decodeURIComponent(escape(items['{{topic}}'])) );
      }

      whiteboard();
      TogetherJS(this);
      TogetherJS.on("ready", function(){
        session = TogetherJS.require('session');
      });
      TogetherJS.reinitialize();


      conn.accept();
  });


  window.onbeforeunload = function() {
    var data = {'queue': '{{ queue }}', 'id': '{{ current_user.id }}',
      'room_id': "{{ room_id }}", 'ip': '{{ ip }}', 'paired_id': '{{ paired_id }}', 'topic': '{{ topic }}'}

    $.ajax({
        url: "{{ url_for('call.remove') }}",
        data: JSON.stringify(data),
        contentType: 'application/json',
        async: false,
        type: 'POST'
    });
  }

  function hangup() {
      Twilio.Device.disconnectAll();
  }


  /* Rate Partner
     - package the rating data and partner ID
     - POST to the user rating endpoint
     - Hide when complete
  */
  $(document).on('click', '#rate_caller', function () {
      var _data = {};
      $('input.rating').each( function() {
          _data[$(this).attr('name')] = $(this).val();
      });
      var data = {
        '_data': _data,
        '_id': partner.id
      };
      $.ajax({
          url: "{{ url_for('user.rate') }}",
          data: JSON.stringify(data),
          contentType: 'application/json',
          async: false,
          type: 'POST',
          success: function(data) {
              var text = '<strong>Thank you for rating your partner! Your input is what makes The Worldphone work!</strong>';
              $('.rate-hide').addClass('hidden');
              $('#rate-call-feedback').removeClass('hidden');
              $('#rate-call-feedback .panel-body').html(text);

          }
      });
      return false;
  });

  /* Report Caller
     -
     - POST to the calls.flag endpoint
  */
  $(document).on('click', '#report_caller', function () {

      var _data = {};
      _data['room_id'] = '{{ room_id }}'
      _data['reporter_id'] = '{{ current_user.id }}'
      _data['reported_id'] = partner.id
      _data['reported_name'] = partner.name
      _data['comment'] = $("[name='flag-comments']").val();
      _data['flags'] = $("[name='flag-type']").val();

      var data = {
        '_data': _data,
      };
      $.ajax({
          url: "{{ url_for('call.flag') }}",
          data: JSON.stringify(data),
          contentType: 'application/json',
          async: false,
          type: 'POST',
          success: function(data) {
              $('#collapseOne .panel-body').html('<strong>Thank you, a report has been sent.</strong>');
          }
      });
      return false;
  });

</script>

<br>
<h3 id="blurb">HEY. We're finding you a partner.</h3>
<br><br>

<button id="hangup_button" class="btn btn-danger hidden" onclick="hangup();">
    Hangup
</button>

<a id="home_button" class="btn btn-warning hidden" href="{{ url_for('user.index') }}">
    Make a new call!
</a>

<br><br>

<div id="ratingContainer" class="hidden">
  <div class="col-lg-12 well" style="margin-bottom:80px;">
      {% include 'call/partials/rate_call.html' %}
  </div>
</div>