theworldphone/modules/admin/forms.py
# -*- coding: utf-8 -*-
"""
    theworldphone.modules.admin.forms
    ~~~~~~~~~~~~~~~~

    admin module forms
"""

from flask.ext.wtf import Form
from wtforms import (HiddenField, SubmitField, SelectField, FileField, DateField)
from wtforms.validators import AnyOf

from theworldphone.extensions import db
from theworldphone.modules.user.constants import UserStatus


class UserForm(Form):
    next = HiddenField()
    status = SelectField(u"Status", [AnyOf([str(s.name) for s in UserStatus])],
            choices=[(str(s.name), s.name.capitalize()) for s in UserStatus])
    created_time = DateField(u'Created time')  # _created_at ?
    submit = SubmitField(u'Save')

    def save(self, user):
        self.populate_obj(user)
        db.session.add(user)
        db.session.commit()


class EditTranslationForm(Form):
    multipart = True
    file = FileField(u"Upload Translation File")
    language = HiddenField()
    submit = SubmitField(u'Save')

theworldphone/__init__.py
# -*- coding: utf-8 -*-

from factory import create_app

theworldphone/modules/admin/__init__.py
# -*- coding: utf-8 -*-

from .views import admin

__all__ = [admin]

theworldphone/modules/admin/views.py
# -*- coding: utf-8 -*-
"""
    theworldphone.modules.admin.views
    ~~~~~~~~~~~~~~~~

    admin module views and controllers
"""

from werkzeug import secure_filename
import os, json, urllib, re, requests, time, datetime

from itertools import chain

from flask import (Blueprint, render_template, request, flash, current_app, send_from_directory,
    redirect, url_for, jsonify, abort)
from flask.ext.login import login_required, login_user, logout_user, current_user
from flask.ext.babel import Babel

from theworldphone.extensions import db
from theworldphone.decorators import admin_required

from theworldphone.modules.frontend.forms import LoginForm
from theworldphone.modules.redis import RedisQueue
from theworldphone.modules.user.models import User, Language
from theworldphone.modules.user.constants import UserRole, COUNTRY_CODES
from theworldphone.modules.call import CallLog
from theworldphone.modules.call.constants import CallType

from .forms import UserForm, EditTranslationForm

admin = Blueprint('admin', __name__, url_prefix='/admin')


# flash(_( -> flash((

@admin.route('/login', methods=['GET', 'POST'])
def login():
    '''
    If user is not logged in:

    1) Show the user the login form.
    2) Handle the input form the login form.

    If user is already logged, send them to user.index or admin.index as appropriate

    If User.authenticate(form.login.data, form.password.data) checks out
    send them to user.index or admin.index as appropriate.

    If the user is banned, flash a message and reshow login form.

    '''
    if current_user.is_authenticated and not current_user.is_admin():
        return redirect(url_for('user.index'))
    elif current_user.is_authenticated and current_user.is_admin():
        return redirect(url_for('admin.index'))

    form = LoginForm(login=request.args.get('login', None),
                     next=request.args.get('next', None))

    if form.validate_on_submit():
        user, authenticated = User.authenticate(form.login.data,
                                    form.password.data)
        if user and authenticated and user.status == 'banned':
            flash(('Sorry, you are not allowed access to your account due to inappropriate behavior.'), 'danger')
        elif user and authenticated and user.status == 'active':
            remember = request.form.get('remember') == 'y'
            if login_user(user, remember=remember):

                if request.environ.get('HTTP_X_REAL_IP', request.remote_addr) not in user._ip_list.values():
                    user._ip_list[datetime.datetime.now()] = request.environ.get('HTTP_X_REAL_IP', request.remote_addr)
                    db.session.commit()

                flash(("Logged in"), 'success')
            if user.is_admin():
                return redirect(url_for('admin.index'))
            else:
                return redirect(form.next.data or url_for('user.index'))
        else:
            flash(('Sorry, invalid login'), 'danger')

    return render_template('frontend/login.html', form=form)


@admin.route('/reauth', methods=['GET', 'POST'])
@login_required
def reauth():
    '''This function allows a user to attempt to log in
    again after a failed attempt.

    **Returns:**
        - Change password view on reauthentication success
        - Reauthentication view on reauthentication failure.

    '''
    form = ReauthForm(next=request.args.get('next'))

    if request.method == 'POST':
        user, authenticated = User.authenticate(current_user.name,
                                    form.password.data)
        if user and authenticated:
            confirm_login()
            current_app.logger.debug('reauth: %s' % session['_fresh'])
            flash(('Reauthenticated.'), 'success')
            return redirect('/change_password')

        flash(('Password is wrong.'), 'danger')
    return render_template('frontend/reauth.html', form=form)


@admin.route('/logout')
@login_required
def logout():
    '''This function logs user out of current session.

    Returns:
        Redirects to login view on success.

    '''
    logout_user()
    flash(('Logged out'), 'success')
    return redirect(url_for('admin.login'))


@admin.route('/')
@login_required
@admin_required
def index():
    """
    # Grab TEFL_PENDING users and flagged calls.
    Grab all users.
    Use those to load admin index page.

    # Returns render_template('admin/index.html', users=users, active='users', calls=calls)
    Returns render_template('admin/users.html', users=users, active='users', title='Users', countries=COUNTRY_CODES)
    """
    # users = User.query.filter_by(_role_code=UserRole.tefl_pending.value)
    # calls = CallLog.query.filter_by(flagged=True)
    # return render_template('admin/index.html',
    #     users=users,
    #     active='users',
    #     calls=calls)
    users = User.query.all()
    return render_template('admin/users.html',
        users=users,
        active='users',
        title='Users',
        countries=COUNTRY_CODES)


@admin.route('/users')
@login_required
@admin_required
def users():
    """
    Get all users and user those to load admin/users/.
    The users view contains a table filled with details about all users in the system.

    Returns render_template('admin/users.html', users=users, active='users')

    """
    users = User.query.all()
    return render_template('admin/users.html',
        users=users,
        active='users',
        title='Users',
        countries=COUNTRY_CODES)


@admin.route('/user/<string:user_uid>', methods=['GET', 'POST'])
@login_required
@admin_required
def user(user_uid):
    """
    Allows the admin to change the following details about the user:

    - _role_code
    - status (_status_code)
    - created_time

    If the user does not exist, returns a 404.

    Returns render_template('admin/user.html')

    """
    user = User.query.filter_by(uid=user_uid).first_or_404()
    form = UserForm(obj=user, next=request.args.get('next'))

    if form.validate_on_submit():
        form.save(user)
        flash('User updated.', 'success')

    return render_template('admin/user.html',
        user=user,
        form=form,
        countries=COUNTRY_CODES)


@admin.route('/ban_user', methods=['POST'])
@login_required
@admin_required
def ban_user():
    """
    Bans a user
    """
    data = json.loads(request.data)
    uids = data['uids']

    if isinstance(uids, list):
        for user_uid in uids:
            ban(user_uid)
        time.sleep(0.75)
        return jsonify(flag='success', message='all users banned.')
    else:
        user_uid = uids
        ban(user_uid)
        time.sleep(0.75)
        return jsonify(flag='success', message='User ' + user_uid + ' was banned.')
    return jsonify(flag='error', message='invalid operation')


@admin.route('/tefl_users')
@login_required
@admin_required
def tefl_users():
    """
    Displays information about all TEFL users.
    Uses the same html as /users/ view
    """
    users = User.query.filter_by(_role_code=UserRole.tefl.value)
    return render_template('admin/users.html',
        users=users,
        active='users',
        title='TEFL Users',
        countries=COUNTRY_CODES)


@admin.route('/pending_tefl_users')
@login_required
@admin_required
def pending_tefl_users():
    """
    Displays information about all pending TEFL users.
    Uses the same html as /users/ view
    """

    users = User.query.filter_by(_role_code=UserRole.tefl_pending.value)
    return render_template('admin/pending_tefl_users.html', users=users, active='users')


@admin.route('/appr_tefl/<string:uid>/<int:code>')
@login_required
@admin_required
def appr_tefl(uid, code):
    """
    Args:
        id (int): id of user
        code (int): 0 is deny, 1 is approve

    Changes User._role_code for a given user in the db.
    """
    user = User().first(uid=uid)
    if code is 0:
        user.role = 'tefl_denied'
        db.session.add(user)
        db.session.commit()
    elif code is 1:
        user.role = 'tefl'
        db.session.add(user)
        db.session.commit()

    users = User.query.filter_by(_role_code=UserRole.tefl_pending.value)
    return render_template('admin/pending_tefl_users.html', users=users, active='users')


@admin.route('/translation/edit/<language>', methods=['POST', 'GET'])
@login_required
@admin_required
def edit_translation(language):
    """
    """
    form = EditTranslationForm(language=language)
    if form.validate_on_submit():
        file = request.files[form.file.name]
        if file:
            filename = secure_filename(file.filename)
            file.save(
                os.path.join(current_app.config['TRANSLATIONS_FOLDER'], language,
                    current_app.config['TRANSLATIONS_PATH'],
                    current_app.config['TRANSALTIONS_FILE']))
            os.system("pybabel compile -f -d theworldphone/translations")
            flash("Translation File has been uploaded")
            return redirect(url_for('admin.edit_translation', language=language))
    return render_template('admin/translation.html', form=form)


@admin.route('/translations', methods=['GET'])
@login_required
@admin_required
def translations():
    babel = Babel(current_app)
    languages = babel.list_translations()
    return render_template('admin/translations.html', languages=languages)


@admin.route('/translation/<language>', methods=['GET'])
@login_required
@admin_required
def existing_translation(language):
    return send_from_directory(os.path.join(
        current_app.config['TRANSLATIONS_FOLDER'],
        language,
        current_app.config['TRANSLATIONS_PATH']),
        current_app.config['TRANSALTIONS_FILE'])


@admin.route('/calls', methods=['GET'])
@login_required
@admin_required
def calls():
    """
    Get all calls and use those to load admin/calls/.
    The calls view contains a table filled with details about all calls in the system.

    return render_template('admin/calls.html', calls=calls)

theworldphone/modules/api/__init__.py
# -*- coding: utf-8 -*-

from .services import api

__all__ = [api]

theworldphone/modules/call/__init__.py
# -*- coding: utf-8 -*-
from .views import call
from .models import CallLog
from .constants import CALL_TYPES

__all__ = [call, CallLog, CALL_TYPES]

theworldphone/modules/frontend/__init__.py
# -*- coding: utf-8 -*-

from .views import frontend

__all__ = [frontend]

theworldphone/modules/mailchimp/__init__.py
# -*- coding: utf-8 -*-

from .services import chimp

__all__ = [chimp]

theworldphone/modules/redis/__init__.py
# -*- coding: utf-8 -*-

from redis_queue import RedisQueue
from redis_hash import RedisHash

__all__ = [RedisQueue, RedisHash]

theworldphone/modules/user/__init__.py
# -*- coding: utf-8 -*-

from .models import User
# from .views import user
from .services import user
from .constants import (USER_ROLE, ADMIN, USER, USER_STATUS, INACTIVE, ACTIVE, BANNED, TEFL_PENDING,
    TEFL, TEFL_DENIED, COUNTRY_CODES, LANGUAGES, TOPICS, GENDER_TYPE)

__all__ = [User, user, USER_ROLE, ADMIN, USER, USER_STATUS,
INACTIVE, ACTIVE, BANNED, TEFL_PENDING, TEFL, TEFL_DENIED, COUNTRY_CODES, LANGUAGES, TOPICS,
GENDER_TYPE]

theworldphone/modules/user/views.py
# -*- coding: utf-8 -*-
"""
    theworldphone.user.views
    ~~~~~~~~~~~~~~~~

    user views and controllers
"""

import json
from uuid import uuid4

from flask import (Blueprint, render_template, request, abort, flash, jsonify, url_for, redirect,
    Response)
from flask.ext.login import login_required, current_user
from flask.ext.babel import lazy_gettext as _

from theworldphone.extensions import db

from .constants import LANGUAGES, TEFL_PENDING, COUNTRY_CODES
from .models import User
from .forms import ProfileForm, PasswordForm


user = Blueprint('user', __name__, url_prefix='/user')


@user.route('/')
@user.route('/<int:offset>')
@login_required
def index(offset=0):
    """
    Creates a uuid4().hex room_id and returns

    render_template('user/index.html', user=current_user, languages=LANGUAGES, room_id=room_id)
    """
    room_id = uuid4().hex
    if current_user.is_authenticated and current_user.is_admin():
        return redirect(url_for('admin.index'))
    else:
        return render_template('user/index.html',
            user=current_user,
            languages=LANGUAGES,
            room_id=room_id)


@user.route('/details')
@login_required
def details(_id=None):
    """
    Returns details of a given user as a dictionary

    .. code-block:: javascript

        {
        'id': int,
        'name': str,
        'location': str,
        'gender': str,
        'overall': float,
        'tefl': bool
        }
    """
    if request.args.get('id'):
        user = User.get_by_id(request.args.get('id'))
        return jsonify(user.to_dict())
    abort(404)


@user.route('/request_tefl/<int:rtype>', methods=['POST'])
@login_required
def request_tefl(rtype):
    data = json.loads(request.data)

    if rtype == 0:
        user = User.get_by_id(int(data['id']))
        setattr(user, 'role_code', TEFL_PENDING)
        db.session.add(user)
        db.session.commit()

        flash("We'll be contacting you soon!", 'success')
    return jsonify({"status": "success"})


@user.route('/rate', methods=['POST'])
@login_required
def rate():
    data = json.loads(request.data)
    user = User.get_by_id(int(data['_id']))
    if user:
        _data = data['_data']
        user.set_ratings(_data)
        db.session.commit()
        return jsonify({'success': 'user vote recorded'})
    return Response(status=500, mimetype='application/json')


@user.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    """
    Return the user/profile view.
    Provides a form which allows the user to change their own

        - email
        - gender_code
        - source_langs
        - target_langs

    Validates form data & commits it to db.

    returns render_template('user/profile.html')
    """
    user = User.query.filter_by(name=current_user.name).first_or_404()
    form = ProfileForm(
        obj=user,
        email=current_user.email,
        role_code=current_user.role_code,
        status_code=current_user.status_code,
        next=request.args.get('next'))

    if form.validate_on_submit():
        form.create_profile(request, user)
        flash('Profile updated.', 'success')

    return render_template('user/profile.html',
        user=user,
        active="profile",
        form=form,
        countries=COUNTRY_CODES)


@user.route('/password', methods=['GET', 'POST'])
@login_required
def password():
    """
        Return the user/profile view.
        Provides a form which allows the user to change their own password
    """
    user = User.query.filter_by(name=current_user.name).first_or_404()
    form = PasswordForm(next=request.args.get('next'))

    if form.validate_on_submit():
        form.update_password(user)

        flash(_('Password updated.'), 'success')

    return render_template('user/password.html',
        user=user,
        active="password",
        form=form)

theworldphone/templates/layouts/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block title %}{{ page_title|default(_('Project')) }}{% endblock %}</title>
        <meta name="description" content="The World Phone">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <link rel="Shortcut Icon" href="{{ url_for('static', filename='client/src/assets/img/favicon.png') }}" type="image/x-icon">

        {% block css %}
        <link rel="stylesheet" href="{{ url_for('static', filename='flat-ui/bootstrap/css/bootstrap.css') }}">
        <link href='http://fonts.googleapis.com/css?family=Nunito:300' rel='stylesheet' type='text/css'>
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
        <link rel="stylesheet" href="{{ url_for('static', filename='flat-ui/css/flat-ui.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='common-files/css/icon-font.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
        {% endblock %}

        {% block extra_css %}
        {% endblock %}

        {% block css_style %}
        {% endblock %}

        {% if current_user.is_authenticated and not current_user.is_admin() %}
        <style type="text/css">
          body:before {
            content: '';
            position: absolute;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            background: url('/static/common-files/img/whtoverlay.png') !important;
            opacity: 0.5;
          }
          body {
            background-image: url("/static/img/bg/bgcall_50.jpg");
            background-size: cover;
            background-repeat: no-repeat;
            background-position: center center;
          }
        </style>
        {% endif %}

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        {% block js_top %}
        {% endblock %}
    </head>

    <body>
        {% include "macros/_ask_user_to_update_ie.html" %}

        {% block topbar %}
        <header class="header-15">
            <div class="container">
                <div class="row">
                    <div class="navbar navbar-fixed-top col-sm-12" role="navigation">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle"></button>
                            {% if current_user.is_authenticated %}
                                {% if current_user.is_admin() %}
                                <a class="brand" href="{{ url_for('admin.index') }}">The World Phone</a>
                                {% endif %}
                            {% endif %}
                         </div>

                        <div class="navbar-collapse collapse">
                            {% if current_user.is_authenticated %}
                            <ul class="nav navbar-nav">
                                {% if current_user.is_admin() %}
                                <li><a href="{{ url_for('admin.users') }}">Users</a></li>
                                <!-- <li class="dropdown">
                                  <a href="#" class="dropdown-toggle" role="button" aria-expanded="false">Users <span class="caret"></span></a>
                                  <ul class="dropdown-menu">
                                    <li><a class="dropdown-link" href="{{ url_for('admin.users') }}">All Users</a></li>
                                    <li class="divider"></li>
                                    <li><a class="dropdown-link" href="{{ url_for('admin.tefl_users') }}">TEFL Users</a></li>
                                    <li><a class="dropdown-link" href="{{ url_for('admin.pending_tefl_users') }}">Pending TEFL Users</a></li>
                                  </ul>
                                </li> -->
                                <li><a href="{{ url_for('admin.calls') }}">Calls</a></li>
                                <!-- <li class="dropdown">
                                  <a href="#" class="dropdown-toggle" role="button" aria-expanded="false">Calls <span class="caret"></span></a>
                                  <ul class="dropdown-menu">
                                    <li><a class="dropdown-link" href="{{ url_for('admin.calls') }}">All Calls</a></li>
                                    <li><a class="dropdown-link" href="{{ url_for('admin.flagged_calls') }}">Flagged Calls</a></li>
                                  </ul>
                                </li> -->
                                <li><a href="{{ url_for('admin.countries') }}">Countries</a></li>
                                {% endif %}

                            </ul>
                            <form class="navbar-form pull-right">
                                <a class="btn btn-success" href="{{ url_for('admin.logout') }}">{{_('LOG OUT')}}</a>
                            </form>

                            {% if not current_user.is_admin() %}
                            <form class="navbar-form pull-right">
                                <a class="btn btn-success" href="{{ url_for('user.index') }}">{{_('MAKE A CALL')}}</a>
                            </form>
                            {% endif %}

                            {% else %}
                            <form class="navbar-form pull-right">
                                <a class="btn btn-success" href="{{ url_for('admin.login') }}"><strong>{{_('LOG IN')}}</strong></a>
                            </form>
                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
            <div class="header-background"></div>
        </header>

        {% endblock %}

        <div id="main-content">

            {% block flash_message %}
                {% with messages = get_flashed_messages(with_categories=True) %}
                    {% if messages %}
                    <div class="container">
                        <div id='flash_message_container'>
                            {% for category, msg in messages %}
                                <div class="alert alert-{{ category }}">
                                    <button type="button" class="close" data-dismiss="alert">×</button>
                                    {{ msg }}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    {% endif %}
                {% endwith %}
            {% endblock %}


            {% block body %}
            {% endblock %}

        </div>

        <!-- footer-14 -->
        <footer class="footer-14 navbar navbar-fixed-bottom hidden-sm hidden-xs">
            <div class="container">
                <a class="pull-left" href="{{ url_for('admin.index') }}">
                    <span style="font-size:26px;margin-bottom: 15px;" class="glyphicon glyphicon-phone-alt"></span>
                </a>
                <div class="social-btns pull-right">
                    <a href="https://www.facebook.com/theworldphone"><div class="fui-facebook"></div><div class="fui-facebook"></div></a>
                    <!-- <a href="#"><div class="fui-twitter"></div><div class="fui-twitter"></div></a> -->
                </div>
                <nav class="hidden">
                    <ul>
                        <li><a class="disabled" href="#">About</a></li>
                        <li><a class="disabled" href="#">Terms</a></li>
                        <li><a class="disabled" href="#">Privacy</a></li>
                    </ul>
                </nav>
            </div>
        </footer>


        {% block js_btm %}
        <script src="{{ url_for('static', filename='flat-ui/js/bootstrap.min.js') }}"></script>
        <script src="{{ url_for('static', filename='common-files/js/modernizr.custom.js') }}"></script>
        <script src="{{ url_for('static', filename='common-files/js/jquery.scrollTo-1.4.3.1-min.js') }}"></script>
        <script src="{{ url_for('static', filename='common-files/js/jquery.parallax.min.js') }}"></script>
        <script src="{{ url_for('static', filename='common-files/js/startup-kit.js') }}"></script>
        <script src="{{ url_for('static', filename='js/script.js') }}"></script>
        <script src="{{ url_for('static', filename='js/flatui-checkbox.js') }}"></script>
        <script src="{{ url_for('static', filename='js/flatui-radio.js') }}"></script>
        {% endblock %}

        {% block extra_js %}
        {% endblock %}

        {% block ga %}
        {% include "macros/_google_analytics.html" %}
        {% endblock %}
    </body>
</html>