theworldphone/modules/admin/forms.py
# -*- coding: utf-8 -*-
"""
    theworldphone.modules.admin.forms
    ~~~~~~~~~~~~~~~~

    admin module forms
"""

from flask.ext.wtf import Form
from wtforms import (HiddenField, SubmitField, SelectField, FileField, DateField)
from wtforms.validators import AnyOf

from theworldphone.extensions import db
from theworldphone.modules.user.constants import UserStatus


class UserForm(Form):
    next = HiddenField()
    status = SelectField(u"Status", [AnyOf([str(s.name) for s in UserStatus])],
            choices=[(str(s.name), s.name.capitalize()) for s in UserStatus])
    created_time = DateField(u'Created time')  # _created_at ?
    submit = SubmitField(u'Save')

    def save(self, user):
        self.populate_obj(user)
        db.session.add(user)
        db.session.commit()


class EditTranslationForm(Form):
    multipart = True
    file = FileField(u"Upload Translation File")
    language = HiddenField()
    submit = SubmitField(u'Save')

theworldphone/__init__.py
# -*- coding: utf-8 -*-

from factory import create_app

theworldphone/modules/admin/__init__.py
# -*- coding: utf-8 -*-

from .views import admin

__all__ = [admin]

theworldphone/modules/admin/views.py
# -*- coding: utf-8 -*-
"""
    theworldphone.modules.admin.views
    ~~~~~~~~~~~~~~~~

    admin module views and controllers
"""

from werkzeug import secure_filename
import os, json, urllib, re, requests, time, datetime

from itertools import chain

from flask import (Blueprint, render_template, request, flash, current_app, send_from_directory,
    redirect, url_for, jsonify, abort)
from flask.ext.login import login_required, login_user, logout_user, current_user
from flask.ext.babel import Babel

from theworldphone.extensions import db
from theworldphone.decorators import admin_required

from theworldphone.modules.frontend.forms import LoginForm
from theworldphone.modules.redis import RedisQueue
from theworldphone.modules.user.models import User, Language
from theworldphone.modules.user.constants import UserRole, COUNTRY_CODES
from theworldphone.modules.call import CallLog
from theworldphone.modules.call.constants import CallType

from .forms import UserForm, EditTranslationForm

admin = Blueprint('admin', __name__, url_prefix='/admin')


# flash(_( -> flash((

@admin.route('/login', methods=['GET', 'POST'])
def login():
    '''
    If user is not logged in:

    1) Show the user the login form.
    2) Handle the input form the login form.

    If user is already logged, send them to user.index or admin.index as appropriate

    If User.authenticate(form.login.data, form.password.data) checks out
    send them to user.index or admin.index as appropriate.

    If the user is banned, flash a message and reshow login form.

    '''
    if current_user.is_authenticated and not current_user.is_admin():
        return redirect(url_for('user.index'))
    elif current_user.is_authenticated and current_user.is_admin():
        return redirect(url_for('admin.index'))

    form = LoginForm(login=request.args.get('login', None),
                     next=request.args.get('next', None))

    if form.validate_on_submit():
        user, authenticated = User.authenticate(form.login.data,
                                    form.password.data)
        if user and authenticated and user.status == 'banned':
            flash(('Sorry, you are not allowed access to your account due to inappropriate behavior.'), 'danger')
        elif user and authenticated and user.status == 'active':
            remember = request.form.get('remember') == 'y'
            if login_user(user, remember=remember):

                if request.environ.get('HTTP_X_REAL_IP', request.remote_addr) not in user._ip_list.values():
                    user._ip_list[datetime.datetime.now()] = request.environ.get('HTTP_X_REAL_IP', request.remote_addr)
                    db.session.commit()

                flash(("Logged in"), 'success')
            if user.is_admin():
                return redirect(url_for('admin.index'))
            else:
                return redirect(form.next.data or url_for('user.index'))
        else:
            flash(('Sorry, invalid login'), 'danger')

    return render_template('frontend/login.html', form=form)


@admin.route('/reauth', methods=['GET', 'POST'])
@login_required
def reauth():
    '''This function allows a user to attempt to log in
    again after a failed attempt.

    **Returns:**
        - Change password view on reauthentication success
        - Reauthentication view on reauthentication failure.

    '''
    form = ReauthForm(next=request.args.get('next'))

    if request.method == 'POST':
        user, authenticated = User.authenticate(current_user.name,
                                    form.password.data)
        if user and authenticated:
            confirm_login()
            current_app.logger.debug('reauth: %s' % session['_fresh'])
            flash(('Reauthenticated.'), 'success')
            return redirect('/change_password')

        flash(('Password is wrong.'), 'danger')
    return render_template('frontend/reauth.html', form=form)


@admin.route('/logout')
@login_required
def logout():
    '''This function logs user out of current session.

    Returns:
        Redirects to login view on success.

    '''
    logout_user()
    flash(('Logged out'), 'success')
    return redirect(url_for('admin.login'))


@admin.route('/')
@login_required
@admin_required
def index():
    """
    # Grab TEFL_PENDING users and flagged calls.
    Grab all users.
    Use those to load admin index page.

    # Returns render_template('admin/index.html', users=users, active='users', calls=calls)
    Returns render_template('admin/users.html', users=users, active='users', title='Users', countries=COUNTRY_CODES)
    """
    # users = User.query.filter_by(_role_code=UserRole.tefl_pending.value)
    # calls = CallLog.query.filter_by(flagged=True)
    # return render_template('admin/index.html',
    #     users=users,
    #     active='users',
    #     calls=calls)
    users = User.query.all()
    return render_template('admin/users.html',
        users=users,
        active='users',
        title='Users',
        countries=COUNTRY_CODES)


@admin.route('/users')
@login_required
@admin_required
def users():
    """
    Get all users and user those to load admin/users/.
    The users view contains a table filled with details about all users in the system.

    Returns render_template('admin/users.html', users=users, active='users')

    """
    users = User.query.all()
    return render_template('admin/users.html',
        users=users,
        active='users',
        title='Users',
        countries=COUNTRY_CODES)


@admin.route('/user/<string:user_uid>', methods=['GET', 'POST'])
@login_required
@admin_required
def user(user_uid):
    """
    Allows the admin to change the following details about the user:

    - _role_code
    - status (_status_code)
    - created_time

    If the user does not exist, returns a 404.

    Returns render_template('admin/user.html')

    """
    user = User.query.filter_by(uid=user_uid).first_or_404()
    form = UserForm(obj=user, next=request.args.get('next'))

    if form.validate_on_submit():
        form.save(user)
        flash('User updated.', 'success')

    return render_template('admin/user.html',
        user=user,
        form=form,
        countries=COUNTRY_CODES)


@admin.route('/ban_user', methods=['POST'])
@login_required
@admin_required
def ban_user():
    """
    Bans a user
    """
    data = json.loads(request.data)
    uids = data['uids']

    if isinstance(uids, list):
        for user_uid in uids:
            ban(user_uid)
        time.sleep(0.75)
        return jsonify(flag='success', message='all users banned.')
    else:
        user_uid = uids
        ban(user_uid)
        time.sleep(0.75)
        return jsonify(flag='success', message='User ' + user_uid + ' was banned.')
    return jsonify(flag='error', message='invalid operation')


@admin.route('/tefl_users')
@login_required
@admin_required
def tefl_users():
    """
    Displays information about all TEFL users.
    Uses the same html as /users/ view
    """
    users = User.query.filter_by(_role_code=UserRole.tefl.value)
    return render_template('admin/users.html',
        users=users,
        active='users',
        title='TEFL Users',
        countries=COUNTRY_CODES)


@admin.route('/pending_tefl_users')
@login_required
@admin_required
def pending_tefl_users():
    """
    Displays information about all pending TEFL users.
    Uses the same html as /users/ view
    """

    users = User.query.filter_by(_role_code=UserRole.tefl_pending.value)
    return render_template('admin/pending_tefl_users.html', users=users, active='users')


@admin.route('/appr_tefl/<string:uid>/<int:code>')
@login_required
@admin_required
def appr_tefl(uid, code):
    """
    Args:
        id (int): id of user
        code (int): 0 is deny, 1 is approve

    Changes User._role_code for a given user in the db.
    """
    user = User().first(uid=uid)
    if code is 0:
        user.role = 'tefl_denied'
        db.session.add(user)
        db.session.commit()
    elif code is 1:
        user.role = 'tefl'
        db.session.add(user)
        db.session.commit()

    users = User.query.filter_by(_role_code=UserRole.tefl_pending.value)
    return render_template('admin/pending_tefl_users.html', users=users, active='users')


@admin.route('/translation/edit/<language>', methods=['POST', 'GET'])
@login_required
@admin_required
def edit_translation(language):
    """
    """
    form = EditTranslationForm(language=language)
    if form.validate_on_submit():
        file = request.files[form.file.name]
        if file:
            filename = secure_filename(file.filename)
            file.save(
                os.path.join(current_app.config['TRANSLATIONS_FOLDER'], language,
                    current_app.config['TRANSLATIONS_PATH'],
                    current_app.config['TRANSALTIONS_FILE']))
            os.system("pybabel compile -f -d theworldphone/translations")
            flash("Translation File has been uploaded")
            return redirect(url_for('admin.edit_translation', language=language))
    return render_template('admin/translation.html', form=form)


@admin.route('/translations', methods=['GET'])
@login_required
@admin_required
def translations():
    babel = Babel(current_app)
    languages = babel.list_translations()
    return render_template('admin/translations.html', languages=languages)


@admin.route('/translation/<language>', methods=['GET'])
@login_required
@admin_required
def existing_translation(language):
    return send_from_directory(os.path.join(
        current_app.config['TRANSLATIONS_FOLDER'],
        language,
        current_app.config['TRANSLATIONS_PATH']),
        current_app.config['TRANSALTIONS_FILE'])


@admin.route('/calls', methods=['GET'])
@login_required
@admin_required
def calls():
    """
    Get all calls and use those to load admin/calls/.
    The calls view contains a table filled with details about all calls in the system.

    return render_template('admin/calls.html', calls=calls)

theworldphone/modules/api/__init__.py
# -*- coding: utf-8 -*-

from .services import api

__all__ = [api]

theworldphone/modules/call/__init__.py
# -*- coding: utf-8 -*-
from .views import call
from .models import CallLog
from .constants import CALL_TYPES

__all__ = [call, CallLog, CALL_TYPES]

theworldphone/modules/frontend/__init__.py
# -*- coding: utf-8 -*-

from .views import frontend

__all__ = [frontend]

theworldphone/modules/mailchimp/__init__.py
# -*- coding: utf-8 -*-

from .services import chimp

__all__ = [chimp]

theworldphone/modules/redis/__init__.py
# -*- coding: utf-8 -*-

from redis_queue import RedisQueue
from redis_hash import RedisHash

__all__ = [RedisQueue, RedisHash]

theworldphone/modules/user/__init__.py
# -*- coding: utf-8 -*-

from .models import User
# from .views import user
from .services import user
from .constants import (USER_ROLE, ADMIN, USER, USER_STATUS, INACTIVE, ACTIVE, BANNED, TEFL_PENDING,
    TEFL, TEFL_DENIED, COUNTRY_CODES, LANGUAGES, TOPICS, GENDER_TYPE)

__all__ = [User, user, USER_ROLE, ADMIN, USER, USER_STATUS,
INACTIVE, ACTIVE, BANNED, TEFL_PENDING, TEFL, TEFL_DENIED, COUNTRY_CODES, LANGUAGES, TOPICS,
GENDER_TYPE]

theworldphone/modules/user/views.py
# -*- coding: utf-8 -*-
"""
    theworldphone.user.views
    ~~~~~~~~~~~~~~~~

    user views and controllers
"""

import json
from uuid import uuid4

from flask import (Blueprint, render_template, request, abort, flash, jsonify, url_for, redirect,
    Response)
from flask.ext.login import login_required, current_user
from flask.ext.babel import lazy_gettext as _

from theworldphone.extensions import db

from .constants import LANGUAGES, TEFL_PENDING, COUNTRY_CODES
from .models import User
from .forms import ProfileForm, PasswordForm


user = Blueprint('user', __name__, url_prefix='/user')


@user.route('/')
@user.route('/<int:offset>')
@login_required
def index(offset=0):
    """
    Creates a uuid4().hex room_id and returns

    render_template('user/index.html', user=current_user, languages=LANGUAGES, room_id=room_id)
    """
    room_id = uuid4().hex
    if current_user.is_authenticated and current_user.is_admin():
        return redirect(url_for('admin.index'))
    else:
        return render_template('user/index.html',
            user=current_user,
            languages=LANGUAGES,
            room_id=room_id)


@user.route('/details')
@login_required
def details(_id=None):
    """
    Returns details of a given user as a dictionary

    .. code-block:: javascript

        {
        'id': int,
        'name': str,
        'location': str,
        'gender': str,
        'overall': float,
        'tefl': bool
        }
    """
    if request.args.get('id'):
        user = User.get_by_id(request.args.get('id'))
        return jsonify(user.to_dict())
    abort(404)


@user.route('/request_tefl/<int:rtype>', methods=['POST'])
@login_required
def request_tefl(rtype):
    data = json.loads(request.data)

    if rtype == 0:
        user = User.get_by_id(int(data['id']))
        setattr(user, 'role_code', TEFL_PENDING)
        db.session.add(user)
        db.session.commit()

        flash("We'll be contacting you soon!", 'success')
    return jsonify({"status": "success"})


@user.route('/rate', methods=['POST'])
@login_required
def rate():
    data = json.loads(request.data)
    user = User.get_by_id(int(data['_id']))
    if user:
        _data = data['_data']
        user.set_ratings(_data)
        db.session.commit()
        return jsonify({'success': 'user vote recorded'})
    return Response(status=500, mimetype='application/json')


@user.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    """
    Return the user/profile view.
    Provides a form which allows the user to change their own

        - email
        - gender_code
        - source_langs
        - target_langs

    Validates form data & commits it to db.

    returns render_template('user/profile.html')
    """
    user = User.query.filter_by(name=current_user.name).first_or_404()
    form = ProfileForm(
        obj=user,
        email=current_user.email,
        role_code=current_user.role_code,
        status_code=current_user.status_code,
        next=request.args.get('next'))

    if form.validate_on_submit():
        form.create_profile(request, user)
        flash('Profile updated.', 'success')

    return render_template('user/profile.html',
        user=user,
        active="profile",
        form=form,
        countries=COUNTRY_CODES)


@user.route('/password', methods=['GET', 'POST'])
@login_required
def password():
    """
        Return the user/profile view.
        Provides a form which allows the user to change their own password
    """
    user = User.query.filter_by(name=current_user.name).first_or_404()
    form = PasswordForm(next=request.args.get('next'))

    if form.validate_on_submit():
        form.update_password(user)

        flash(_('Password updated.'), 'success')

    return render_template('user/password.html',
        user=user,
        active="password",
        form=form)

theworldphone/templates/frontend/change_password.html
{% from "macros/_form.html" import render_field %}

{% set page_title = "Update Your Password" %}

{% extends "layouts/base.html" %}

{% block body %}
  <div class="row">
    <h3>&nbsp;</h3>
    <div class="col-md-4 col-md-offset-4">
      <div class="login-panel panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">Change Password</h3>
          </div>
          <div class="panel-body">

            <form method="post">
              <fieldset>

                {{ form.csrf_token }}
                {{ render_field(form.password, class="form-control", placeholder="") }}
                {{ render_field(form.password_again, class="form-control", placeholder="") }}

                <button type="submit" id="save" class="btn btn-lg btn-info btn-block">Save</button>

              </fieldset>
            </form>

        </div>
      </div>
    </div>
  </div>
{% endblock %}

theworldphone/templates/frontend/layout.html
{% extends "layouts/base.html" %}

{% block css_style %}
<style type="text/css">

  body:before {
    content: '';
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    background: url('static/common-files/img/overlay.png');
    opacity: 0.5;
  }

  body {
    background-color: #e4e4e4;
    background-image: url("/static/img/bg/logout.jpg");
    background-size: cover;
    background-repeat: no-repeat;
    background-position: center center;
  }
</style>

{% endblock %}

theworldphone/templates/frontend/login.html
{% from "macros/_form.html" import render_form, render_field, render_checkbox %}

{% set page_title = "Log In" %}

{% extends "frontend/layout.html" %}

{% block body %}
    <div class="row">
      <h3>&nbsp;</h3>
        <div class="col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">

          <div class="panel panel-default">
              <div class="panel-heading">
                  <h1 class="panel-title">{{_('Sign In')}}</h1>
              </div>
              <div class="panel-body">
                <div>
                  <form method="POST">
                      {{ form.csrf_token }}
                      {{ render_field(form.login, class="form-control", placeholder="username") }}
                      {{ render_field(form.password, class="form-control", placeholder="password") }}
                      {{ render_checkbox(form.remember) }}
                      <button type="submit" id="sign_in" class="btn btn-lg btn-info btn-block">{{_('Sign in')}}</button>
                  </form>
                </div>
                <br>
                <hr>
                <div class="row">
                  <div class="col-sm-12 text-right">
                    <br>
                  </div>
                </div>
              </div>
          </div>

        </div>
    </div>

    <!-- hack for FLat-UI checkboxes -->
    <script type="text/javascript">
        $(document).on('click', "label[for='remember']", function() {
            $(this).toggleClass('checked');
        });
    </script>
{% endblock %}

theworldphone/templates/frontend/reauth.html
{% from "macros/_form.html" import render_form %}

{% set page_title = "Reauthenticate" %}

{% extends "layouts/base.html" %}

{% block body %}
<h2>{{_('Reauthenticate')}}</h2>
{{ render_form(url_for('admin.reauth'), form)}}
{% endblock %}

theworldphone/templates/frontend/reset_password.html
{% from "macros/_form.html" import render_field %}

{% set page_title = "Reset password" %}

{% extends "frontend/layout.html" %}

{% block body %}
<div class="row">
  <h3>&nbsp;</h3>
    <div class="col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">

      <div class="panel panel-default">
          <div class="panel-heading">
              <h1 class="panel-title">{{_('Reset My Password')}}</h1>
          </div>
          <div class="panel-body">
            <div>
                <form method="POST">
                    {{ form.csrf_token }}
                    {{ render_field(form.email, class="form-control", placeholder="email") }}
                    <button type="submit" id="reset" class="btn btn-lg btn-info btn-block">{{_('Reset Password')}}</button>
                </form>
            </div>
          </div>
      </div>

    </div>
</div>
{% endblock %}

theworldphone/templates/frontend/search.html
{% from 'macros/_misc.html' import render_pagination, render_user_table %}

{% extends 'layouts/base.html' %}

{% if keywords %}
    {% set page_title = _('Search results for "%(keywords)s"', keywords=keywords) %}
{% else %}
    {% set page_title = _('Keywords needed!') %}
{% endif %}

{% block body %}
    {% if pagination and pagination.pages > 0 %}
        <p>{% trans total=pagination.total, keywords=keywords %}<strong>{{ total }}</strong> found for your search "<strong>{{ keywords }}</strong>".{% endtrans %}</p>
        {{ render_user_table(pagination.items, 'zebra-striped') }}
        {{ render_pagination(pagination, 'frontend.search') }}
    {% else %}
        <p>{% trans keywords=keywords %}Sorry, Nothing found for your search "<strong>{{ keywords }}</strong>".{% endtrans %}</p>
    {% trans %}
    <p>Suggestions:</p>
    <ul>
       <li>Make sure all words are spelled correctly.</li>
       <li>Try different keywords.</li>
       <li>Try more general keywords.</li>
    </ul>
    {% endtrans %}
    {% endif %}
{% endblock %}

theworldphone/templates/frontend/signup.html
{% from "macros/_form.html" import render_field, render_checkbox %}

{% set page_title = 'Sign Up' %}

{% extends "frontend/layout.html" %}

{% block body %}
<div class="row">
  <h3>&nbsp;</h3>
    <div class="col-sm-6 col-sm-offset-3 col-md-8 col-md-offset-2">

      <div class="panel panel-default">
          <div class="panel-heading">
              <h1 class="panel-title">{{_('Sign Up')}}</h1>
          </div><!-- /.panel-title -->

          <div class="panel-body">

            <form method="POST" id="signup-form">

              <div class="col-md-6">
                {{ form.csrf_token }}
                {{ render_field(form.name, class="form-control", placeholder="username") }}
                {{ render_field(form.email, class="form-control", placeholder="email") }}
              </div>

              <div class="col-md-6">
                <div id="country-typeahead">
                  {{ render_field(form.location, class="typeahead form-control", placeholder="Where are you from?") }}
                </div>
                <span class="hidden">{{ render_checkbox(form.agree) }}</span>
              </div>

              <div class="col-md-12">
                <button type="submit" id="submit" class="btn btn-lg btn-info btn-block">{{_('Register')}}</button>
              </div>

            </form>
          </div>
          <div class="panel-footer panel-default text-right">
              <a href="{{ url_for('admin.login') }}">{{_('Already Registered?')}}</a>
          </div>
      </div>

    </div>
</div>
{% endblock %}

{% block css_style %}
<style type="text/css">
  body:before {
    content: '';
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    background: url('static/common-files/img/overlay.png');
    opacity: 0.5;
  }

  body {
    background-image: url("/static/img/bg/logout.jpg");
    background-size: cover;
    background-repeat: no-repeat;
    background-position: center center;
  }
  span.twitter-typeahead .tt-dropdown-menu {
    position: absolute;
    top: 100%;
    left: 0;
    z-index: 1000;
    display: none;
    float: left;
    min-width: 160px;
    padding: 5px 0;
    margin: 2px 0 0;
    list-style: none;
    font-size: 14px;
    text-align: left;
    background-color: #ffffff;
    border: 1px solid #cccccc;
    border: 1px solid rgba(0, 0, 0, 0.15);
    border-radius: 4px;
    -webkit-box-shadow: 0 6px 12px rgba(0, 0, 0, 0.175);
    box-shadow: 0 6px 12px rgba(0, 0, 0, 0.175);
    background-clip: padding-box;
  }
  span.twitter-typeahead .tt-suggestion > p {
    display: block;
    padding: 3px 20px;
    clear: both;
    font-weight: normal;
    line-height: 1.42857143;
    color: #333333;
    white-space: nowrap;
  }
  span.twitter-typeahead .tt-suggestion > p:hover,
  span.twitter-typeahead .tt-suggestion > p:focus {
    color: #ffffff;
    text-decoration: none;
    outline: 0;
    background-color: #428bca;
  }
  span.twitter-typeahead .tt-suggestion.tt-cursor {
    color: #ffffff;
    background-color: #428bca;
  }
  span.twitter-typeahead {
    width: 100%;
  }
  .input-group span.twitter-typeahead {
    display: block !important;
  }
  .input-group span.twitter-typeahead .tt-dropdown-menu {
    top: 32px !important;
  }
  .input-group.input-group-lg span.twitter-typeahead .tt-dropdown-menu {
    top: 44px !important;
  }
  .input-group.input-group-sm span.twitter-typeahead .tt-dropdown-menu {
    top: 28px !important;
  }
  #countries-typeahead .tt-dropdown-menu {
    max-height: 150px;
    overflow-y: scroll;
  }
</style>
{% endblock %}

{% block extra_js %}
<script src="{{ url_for('static', filename='vendor/typeahead.js/dist/typeahead.bundle.min.js') }}"></script>
<script>
  var substringMatcher = function(strs) {
    return function findMatches(q, cb) {
      var matches, substrRegex;

      // an array that will be populated with substring matches
      matches = [];

      // regex used to determine if a string contains the substring `q`
      substrRegex = new RegExp(q, 'i');

      // iterate through the pool of strings and for any string that
      // contains the substring `q`, add it to the `matches` array
      $.each(strs, function(i, str) {
        if (substrRegex.test(str)) {
          // the typeahead jQuery plugin expects suggestions to a
          // JavaScript object, refer to typeahead docs for more info
          matches.push({ value: str });
        }
      });

      cb(matches);
    };
  };

  var countries = {{ countries|safe }}

  $('#country-typeahead .typeahead').typeahead({
    hint: false,
    highlight: false,
    minLength: 2
  },
  {
    name: 'countries',
    displayKey: 'value',
    source: substringMatcher(countries)
  });
</script>
{% endblock %}

theworldphone/templates/frontend/verify_email.html
{% from "macros/_form.html" import render_field, render_checkbox %}

{% set page_title = 'Verify Email' %}

{% extends "frontend/layout.html" %}

{% block body %}
<div class="row">
  <h3>&nbsp;</h3>
    <div class="col-sm-6 col-sm-offset-3 col-md-8 col-md-offset-2">

      <div class="panel panel-default">
          <div class="panel-heading">
              <h1 class="panel-title">{{_('Verify your email')}}, "{{ user.name }}"</h1>
          </div><!-- /.panel-title -->

          <div class="panel-body">
            <form method="POST">
              <div class="col-md-6">
                {{ form.csrf_token }}
                {{ form.activation_key }}
                {{ render_field(form.password, class="form-control", placeholder="password") }}
                {{ render_field(form.password_again, class="form-control", placeholder="confirm password") }}
                <p class="help-block">Please set a new password</p>
              </div>

              <div class="col-md-6">
                {{ render_field(form.gender_code, class="form-control") }}

                {{ render_field(form.source_langs, id="native-language", multiple="multiple") }}

                {{ render_field(form.target_langs, id="target-language", multiple="multiple") }}
              </div>

              <button type="submit" id="submit" class="btn btn-lg btn-info btn-block">{{_('Verify')}}</button>

            </form>
          </div>
      </div>

    </div>
</div>
{% endblock %}

{% block css_style %}
<link rel="stylesheet" href="{{ url_for('static', filename='vendor/flag-icon-css/css/flag-icon.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='vendor/bootstrap-multiselect/dist/css/bootstrap-multiselect.css') }}"/>
<style type="text/css">
  body:before {
    content: '';
    position: absolute;
    left: 0;
    top: 0;
    width: 100%;
    height: 100%;
    background: url('static/common-files/img/overlay.png');
    opacity: 0.5;
  }

  body {
    background-image: url("/static/img/bg/logout.jpg");
    background-size: cover;
    background-repeat: no-repeat;
    background-position: center center;
  }
</style>
{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="{{ url_for('static', filename='vendor/bootstrap-multiselect/dist/js/bootstrap-multiselect.js') }}"></script>

<script type="text/javascript">
    $(document).ready(function() {
        $('#native-language').multiselect({
            buttonWidth: '100%',
            nonSelectedText: 'Select at least one',
            templates: {

            }
        });
        $('#target-language').multiselect({
            buttonWidth: '100%',
            nonSelectedText: 'Select at least one',
            templates: {

            }
        });
    });
</script>
{% endblock %}